### ISSUE TITLE
是否可以兼容一下gorm的结构体

### ISSUE THREAD

**Issue by BrettCao** [golang-module/carbon#1]

**Comment by gouguoyin** [comment]
已支持gorm结构体，具体用法参考readme.md文件最下面在gorm中的用法

**Comment by almas1992** [comment]
我觉得兼容gorm只实现 `sql.Scanner` 和 `driver.Valuer` 接口就可以，然后在gorm结构体中字段类直接使用 `carbon.Carbon` （目前carbon结构体是为 Unexported），这样就不会侵入代码，毕竟使用该包的人都会使用gorm。
