### ISSUE TITLE
关于是否是有效时间/日期的疑问

### ISSUE THREAD

**Issue by yibin001** [golang-module/carbon#102]
pp := carbon.Parse("2021-13-10 00:00:00")

fmt.Println(pp.IsInvalid()) //输出 true

fmt.Println(pp.Time).  //输出 0001-01-01 00:00:00 +0000 UTC

这里是不是有问题？IsInvalid()只是校验格式吗？

**Comment by gouguoyin** [comment]
目前是只校验格式

**Comment by gouguoyin** [comment]
IsInvalid是判断是否是无效日期，返回true，说明就是无效日期
