### ISSUE TITLE
panic: time: missing Location in call to Time.In

### ISSUE THREAD

**Issue by fenggolang** [golang-module/carbon#103]
github.com/golang-module/carbon/v2 v2.0.0

![image](https://user-images.githubusercontent.com/16982786/138488947-15c85ff5-c053-4cf3-89a8-f9a39d63cf60.png)

**Comment by gouguoyin** [comment]
你定义的a.CreatedAt是carbon.Time类型，不是carbon类型，不能使用Carbon2Time方法

**Comment by piupuer** [comment]
你好，我最近升级到v2.0.1也遇到类似问题，我用的是carbon.DateTime，不管是carbon.Time还是carbon.DateTime，它们都属于Carbon类型不是吗？我觉得应该是t.loc=nil造成的。而1.5.x就没有这个问题
https://github.com/golang-module/carbon/blob/v2.0.1/carbon.go#L177

**Comment by gouguoyin** [comment]
carbon.Time(v1.5)或carbon.time(v2.0)属于time.Time类型，carbon.DateTime属于Carbon类型

**Comment by gouguoyin** [comment]
carbon.Time(v1.5)或carbon.time(v2.0)属于time.Time类型，carbon.DateTime属于Carbon类型

**Comment by gouguoyin** [comment]
carbon.Time(v1.5)或carbon.time(v2.0)属于time.Time类型，carbon.DateTime属于Carbon类型

**Comment by gouguoyin** [comment]
carbon.Time(v1.5)或carbon.time(v2.0)属于time.Time类型，carbon.DateTime属于Carbon类型

**Comment by piupuer** [comment]
感谢来信，但您所发的用户不在服务区，请稍后再发！
