### ISSUE TITLE
关于CreateFromTimestamp的问题

### ISSUE THREAD

**Issue by prosejazz** [golang-module/carbon#104]
根据时间戳的长度判断是毫秒还是微秒不准确

毫秒级在接近1970年时会被误认为单位是秒

**Comment by gouguoyin** [comment]
你有什么好的建议？

**Comment by gouguoyin** [comment]
> 根据时间戳的长度判断是毫秒还是微秒不准确
> 
> 毫秒级在接近1970年时会被误认为单位是秒

能举个例子吗？

**Comment by prosejazz** [comment]
假如我时间选择器上选择了时间1970-01-20 06:45:49，获得毫秒级时间戳1637149000
这时因为时间戳长度为10，会被认为单位是秒，存入数据库时间就成了2021-11-17 19:41:52

比如再极端些，时间戳长度不足10，这个时候转换得到的时间统统都是1970-01-01 08:00:00

建议CreateFromTimestamp 增加一个参数指定单位

**Comment by junchuanwang** [comment]
所有秒以下的精度都会被忽略

话说为什么不直接就加api得了，像time.Unix(),time.UnixMilli, ... 那样

**Comment by gouguoyin** [comment]
> 所有秒以下的精度都会被忽略
> 
> 话说为什么不直接就加api得了，像time.Unix(),time.UnixMilli, ... 那样

新版本会优化

**Comment by gouguoyin** [comment]
v2.1.0版本已发布
* 增加对 go1.18 版本的兼容支持
* 新增CreateFromTimestampMilli()、CreateFromTimestampMicro()、CreateFromTimestampNano()、CreateFromDateTimeMilli()、CreateFromDateTimeMicro()、CreateFromDateTimeNano()方法
* 新增TimestampMilli()、TimestampMicro()、TimestampNano()方法
* 新增DateTime()、Time()方法
* 新增ToDateTimeMilliString()、ToDateTimeMicroString()、ToDateTimeNanoString()、ToShortDateTimeMilliString()、ToShortDateTimeMicroString()、ToShortDateTimeNanoString()、ToRfc3339MilliString()、ToRfc3339MicroString()方法
* 新增SetDateTime()、SetDate()、SetTime()方法
* 新增TimestampMilli、TimestampMicro、TimestampNano结构体
* Parse()方法增加对RFC3339、RFC3339Milli、RFC3339Micro、RFC3339Nano等格式的解析支持
* 精简优化代码，提取公共方法
