### ISSUE TITLE
v2版本api用法是不是全都变了

### ISSUE THREAD

**Issue by Flipped199** [golang-module/carbon#106]
稳定全是旧版本的，难受，顺便请教下如果搭配gorm，在deleted_at字段用carbon.DataTime类型，如何做到软删除呢，感谢

**Comment by gouguoyin** [comment]
v2版本哪里不稳定，能举例么？

**Comment by gouguoyin** [comment]
v2版本是调整了一些api，具体更改内容可以看更新日志
https://github.com/golang-module/carbon/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97

**Comment by Flipped199** [comment]
> v2版本是调整了一些api，具体更改内容可以看更新日志 https://github.com/golang-module/carbon/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97

哦哦，对不起，新手不太清楚更新日志的位置，给大佬添麻烦了，另外，我想请教的是，gorm软删除的话字段类型设置的是gorm.DeletedAt,我也想用carbon.DateTime类型，但是这样做的话就直接硬删除了，了解到carbon是支持gorm的，想请教下如何修改能达到我的目的呢，再次感谢

**Comment by gouguoyin** [comment]
暂时还不支持软删除

**Comment by Flipped199** [comment]
> 暂时还不支持软删除

好的，感谢耐心解答
