### ISSUE TITLE
时间比较函数的BUG

### ISSUE THREAD

**Issue by hyue418** [golang-module/carbon#107]
carbon.Parse(“2022-2-17”).Compare(">", carbon.Parse(“2021-11-16”))
以上返回的结果本应为true，但结果却为false
将2022-2-17改为2022-02-17则正常

**Comment by gouguoyin** [comment]
2022-2-17 不是标准时间格式，需要指定格式

> carbon.ParseByFormat(“2022-2-17”, "Y-n-d").Compare(">", carbon.Parse(“2021-11-16”))

**Comment by hyue418** [comment]
> 2022-2-17 不是标准时间格式，需要指定格式
> 
> > carbon.ParseByFormat(“2022-2-17”, "Y-n-d").Compare(">", carbon.Parse(“2021-11-16”))

这个感觉应该加个自动判断可能好一些，前端传参不太固定，容易会有坑

**Comment by gouguoyin** [comment]
> > 2022-2-17 不是标准时间格式，需要指定格式
> > > carbon.ParseByFormat(“2022-2-17”, "Y-n-d").Compare(">", carbon.Parse(“2021-11-16”))
> 
> 这个感觉应该加个自动判断可能好一些，前端传参不太固定，容易会有坑

如果前端传参不固定，没办法自动判断，假如前端传的是2022-2-3、22-2-3、2022/2/17、2022/02/17或者其他非标准格式这怎么自动判断？

**Comment by hyue418** [comment]
> > > 2022-2-17 不是标准时间格式，需要指定格式
> > > > carbon.ParseByFormat(“2022-2-17”, "Y-n-d").Compare(">", carbon.Parse(“2021-11-16”))
> > 
> > 
> > 这个感觉应该加个自动判断可能好一些，前端传参不太固定，容易会有坑
> 
> 如果前端传参不固定，没办法自动判断，假如前端传的是2022-2-3、22-2-3、2022/2/17、2022/02/17或者其他非标准格式这怎么自动判断？

好的，感谢解答，我自己想办法看怎么处理好一些
