### ISSUE TITLE
可否增加两个时间差的整数差？

### ISSUE THREAD

**Issue by mchongjs** [golang-module/carbon#108]
目前DiffIn和DiffInWithAbs函数都是计算的两个时间的数值差，比如例子中的"2020-08-05 13:14:15"和"2020-08-04 13:14:15"，这两个时间相差是1天，但是"2020-08-05 14:14:15"和"2020-08-05 13:14:15"之间用diffindays函数出来就是0天，希望有个函数能得到这两个日期之间差是1天。

**Comment by gouguoyin** [comment]
可以把两个日期都先转化成年月日形式再计算时间差，如

> c1:=carbon.Parser("2020-08-05 14:14:15").ToDateTime()
> c2:=carbon.Parser("2020-08-05 13:14:15").ToDateTime()
> c1. DiffInDays(c2) //1

**Comment by mchongjs** [comment]
明白了
