### ISSUE TITLE
duration format

### ISSUE THREAD

**Issue by xdxiaodong** [golang-module/carbon#110]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by gouguoyin** [comment]
what？

**Comment by xdxiaodong** [comment]
> what？

https://day.js.org/docs/en/durations/format

**Comment by xdxiaodong** [comment]
> 



> what？

https://day.js.org/docs/en/durations/format

**Comment by gouguoyin** [comment]
现有的方法已经能满足，你具体讲下你的需求

**Comment by xdxiaodong** [comment]
比如druation值是86420100(毫秒)，我想把这个值格式化成"x天x小时x分钟x秒x毫秒"这个字符串显示
