### ISSUE TITLE
请问difference里的各个function为何参数都是不定参数？

### ISSUE THREAD

**Issue by 13sai** [golang-module/carbon#116]
看代码只是比较了最后一个参数，不太明白，所以请教下是有什么特殊设计用途吗？

**Comment by gouguoyin** [comment]
difference里使用不定参数，没有传参数时是和当前时间进行比较，有参数时是与所传参数比较，理论上只能传一个参数，为防止多传，所以取最后一个。

**Comment by 13sai** [comment]
原来

> difference里使用不定参数，没有传参数时是和当前时间进行比较，有参数时是与所传参数比较，理论上只能传一个参数，为防止多传，所以取最后一个。

理解了，谢谢解答
