### ISSUE TITLE
将EndOfDay()的carbon作为SQL参数时的问题

### ISSUE THREAD

**Issue by CloudyCity** [golang-module/carbon#123]
该问题不是`carbon`和`gorm`的bug。

用例如下:

```golang
start := carbon.Parse("2022-04-19").StartOfDay()
end := carbon.Parse("2022-04-19").EndOfDay()
err := global.DB.Table("test").Where("created_at BETWEEN ? AND ?", start, end).Find(&test).Error
```

最终执行到`go-sql-driver`里end参数被转化为`time.Time`：
![image](https://user-images.githubusercontent.com/17662451/163910888-44f00ae2-0c52-429e-bd93-f07449167f60.png)

此时实际筛选出的结果是2022-04-19 00:00:00 至 2022-04-20 00:00:00，原因是2022-04-19.999999999被“四舍五入”为2022-04-20 00:00:00.000000000

如果改为以下写法，可能遗漏掉部分数据：
```golang
err := global.DB.Table("test").Where("created_at BETWEEN ? AND ?", start, end.ToDateTimeString()).Find(&test).Error
```

目前的方案如下：
```golang
start := carbon.Parse("2022-04-19").StartOfDay()
end := carbon.Parse("2022-04-19").AddDay().StartOfDay()
err := global.DB.Table("test").Where("created_at >= ? AND created_at <= ?", start, end).Find(&test).Error
```

最后问题是，是否存在更优的解决方案？

**Comment by gouguoyin** [comment]
start := carbon.Parse("2022-04-19").StartOfDay().ToDateTimeString()
end := carbon.Parse("2022-04-19").EndOfDay().ToDateTimeString()
err := global.DB.Table("test").Where("created_at BETWEEN ? AND ?", start, end).Find(&test).Error

**Comment by CloudyCity** [comment]
> ```go
> start := carbon.Parse("2022-04-19").StartOfDay().ToDateTimeString()
> end := carbon.Parse("2022-04-19").EndOfDay().ToDateTimeString()
> err := global.DB.Table("test").Where("created_at BETWEEN ? AND ?", start, end).Find(&test).Error
> ```

数据库的`created_at`的精度为毫秒的话，使用`ToDateTimeString()`精确到秒进行筛选会遗漏部分数据，使用`ToDateTimeNanoString()`精确到纳秒会出现“四舍五入”问题，使用`ToDateTimeMicroString()`可以解决~，mysql的最大精度也正好也只是到毫秒。

**Comment by gouguoyin** [comment]
麻烦支持下，给个star
