### ISSUE TITLE
时间格式能否支持go time库的时间格式 

### ISSUE THREAD

**Issue by duxphp** [golang-module/carbon#127]
时间格式能否安装go time库的时间格式，不然记忆会有问题  标准库的 2006-01-02 15:04:05  遵循了 1 2 3 4 5 6 进行排列便于记忆  carbon 的 2020-08-05 13:14:15 遵循的是那种规则呢 或者可以兼容两种格式

**Comment by gouguoyin** [comment]
ParseByLayout()方法可以支持go time库的时间格式的解析
```go
carbon.ParseByLayout("2020|08|05 13|14|15", "2006|01|02 15|04|05").ToDateTimeString() // 2020-08-05 13:14:15
```

**Comment by gouguoyin** [comment]
2020-08-05 13:14:15 不是格式，而是需要解析的示例日期
