### ISSUE TITLE
Parse() cannot parse a time string like this: 2022-5-18

### ISSUE THREAD

**Issue by zmou** [golang-module/carbon#131]
The Parse() method cannot parse a time string when the month or date less than 10 is not preceded by 0, like this: `2022-5-18`
Code sample:
```
carbon.Parse("2020-8-05").ToDateTimeString() // empty string
```
Do need to support this less formal time format string, thank you!

**Comment by gouguoyin** [comment]
"2020-8-05" is not a standard time format, you can use 
```go
carbon.ParseByLayout("2020-8-05", "2006-1-02")
```
or
```go
carbon.ParseByFormat("2020-8-05", "Y-n-d")
```

**Comment by zmou** [comment]
> 



> "2020-8-05" is not a standard time format, you can use
> 
> ```go
> carbon.ParseByLayout("2020-8-05", "2006-1-02")
> ```
> 
> or
> 
> ```go
> carbon.ParseByFormat("2020-8-05", "Y-n-d")
> ```

However, such analysis is not feasible for data sources that are not uniform or standardized, such as: 
```
2020-8-5, 2020-08-5, 2020-8-05, 2020-8-5 12:00:00
```
Is it possible to use string splitting to unify the non-standard input into the canonical one, so that we do not need to care too much about the format of the input, as long as it is a normal time format, not too canonical.

**Comment by gouguoyin** [comment]
If these non-standard formats need to be considered, the following formats must also be considered：
```
2020-8-5,
2020-8-5 1:02:03,
2020-8-5 01:02:03,
2020-8-5 01:2:03,
2020-8-5 01:02:3,
2020-08-5, 
2020-08-5 1:02:03,
2020-08-5 01:02:03,
2020-08-5 01:2:03,
2020-08-5 01:02:3,
2020-8-05, 
2020-8-05 1:02:03,
2020-8-05 01:02:03,
2020-8-05 01:2:03,
2020-8-05 01:02:3
```

**Comment by zmou** [comment]
> 

If possible, consider these non-standard formats.

**Comment by gouguoyin** [comment]
Already under development, the next version will be compatible

**Comment by gouguoyin** [comment]
It has been compatible in 1.7.0 or 2.2.0
