### ISSUE TITLE
function for the same date-time

### ISSUE THREAD

**Issue by pjh591029530** [golang-module/carbon#133]
In order to determine whether two dates are the same day
code like:
```go
func (c Cron) IsTheSameDay(t Carbon) bool {
    if c.Format("Ymd") == t.Format("Ymd") {
        return true 
    } 
    return false 
}
```

**Comment by gouguoyin** [comment]
The v2.1.7 version released today has added `IsSameXXX()` series methods, such as `IsSameYear()`

**Comment by gouguoyin** [comment]
> In order to determine whether two dates are the same day code like:
> 
> ```go
> func (c Cron) IsTheSameDay(t Carbon) bool {
>     if c.Format("Ymd") == t.Format("Ymd") {
>         return true 
>     } 
>     return false 
> }
> ```
The above code is not concise enough, you can write like this
```go
func (c Cron) IsTheSameDay(t Carbon) bool {
    return c.Format("Ymd") == t.Format("Ymd")
}
```
