### ISSUE TITLE
Why Time2Carbon() doesn't set Carbon's loc to the input time's loc

### ISSUE THREAD

**Issue by lucas-57blocks** [golang-module/carbon#144]
// Time2Carbon converts time.Time to Carbon.
// 将 time.Time 转换成 Carbon
func Time2Carbon(tt time.Time) Carbon {
	c := NewCarbon()
	c.time = tt
	return c
}

NewCarbon() 得到的 loc 是运行时环境的 loc, 但是输入的 tt 的 loc 可能是另一个 loc, 这会导致后续如 EndOfDay() 等方法的计算出来的时间的 loc 都是运行时环境的 loc，不是输入 tt 的 loc。

**Comment by gouguoyin** [comment]
Fixed in version 2.1.9
