### ISSUE TITLE
u format is NOT padded to 3

### ISSUE THREAD

**Issue by endlesstravel** [golang-module/carbon#145]
Hello,  my issue is ` u format is NOT padded to 3 `

I encountered an issue with the following code:
```go
// c is carbon.Carbon
c.Format("u")
```
golang version:  1.18
carbon version: v2.1.8
time zone: default

I expected to get:  040

```
040
```
But I actually get:

```
40
```

Thanks!

**Comment by endlesstravel** [comment]
screenshot
![image](https://user-images.githubusercontent.com/10757838/179337093-ff2a12e9-9cf9-49a9-af32-87d53dc6ebf4.png)
![image](https://user-images.githubusercontent.com/10757838/179337103-239955ac-7728-47a2-ae17-6f4f150dfe31.png)

**Comment by gouguoyin** [comment]
The value range of the u symbol is 0-999. If you want to keep 3 bits of padding, you can do it like the following:
```go
fmt.Sprintf("%03d", c.Format("u"))
```

**Comment by gouguoyin** [comment]
Documentation has been updated
