### ISSUE TITLE
README Not have `ToStartTimeString` function

### ISSUE THREAD

**Issue by SliverHorn** [golang-module/carbon#146]
in the [README.md](https://github.com/golang-module/carbon#start-and-end)
```go
// Start of the month
carbon.Parse("2020-08-05 13:14:15").StartOfMonth().ToStartTimeString() // 2020-08-01 00:00:00
```

but in the [README.jp.md](https://github.com/golang-module/carbon/blob/master/README.jp.md#%E5%A7%8B%E3%81%BE%E3%82%8A%E3%81%A8%E7%B5%82%E3%82%8F%E3%82%8A)
```go
// 本月の始まり
carbon.Parse("2020-08-05 13:14:15").StartOfMonth().ToDateTimeString() // 2020-08-01 00:00:00
```
and in the [README.cn.md](https://github.com/golang-module/carbon/blob/master/README.cn.md#%E5%BC%80%E5%A7%8B%E6%97%B6%E9%97%B4%E7%BB%93%E6%9D%9F%E6%97%B6%E9%97%B4)

```go
// 本月开始时间
carbon.Parse("2020-08-05 13:14:15").StartOfMonth().ToDateTimeString() // 2020-08-01 00:00:00
```

I searched the whole project and didn't find the function `ToStartTimeString`. If it is intentional, please also specify, if not, please accept my pr

**Comment by gouguoyin** [comment]
Thanks
