### ISSUE TITLE
Time2Carbon() v2.19 has forward compatibility issues

### ISSUE THREAD

**Issue by liugang** [golang-module/carbon#149]
>  优化 Time2Carbon() 方法，从 time.Time 里提提取时区作为当前时区

这个有向前兼容性问题, 以前我用的时候, 全部是time.Local的, 现在全部是time.UTC了, 我这边所有的代码都必须添加: .SetLocation(time.Local)

比如:

```go
carbon.Time2Carbon(user.Time).ToDateTimeString(),
```
必须改为
```go
carbon.Time2Carbon(user.Time).SetLocation(time.Local).ToDateTimeString(),
```

我的使用场景:

1. user.Time字段以time.Time 存入mongo数据库(iso8601格式, utc时间);
2. 从mongo查询出来, user.Time 读出来, 里面的时区就是utc时间

升级carbon之前, Time2Carbon 是默认为time.Local的, 现在升级到2.19之后, 默认是time.UTC的了.

> 根本原因: 时间经过数据库存取之后,会丢失timeZone信息(全部是UTC时间),需要客户的自己指定是哪个时区

也许你这样改有你的理由吧, 但是真的破坏了向前兼容性. 需要在release着重说明一下, 不然已经上线的产品,升级之后全部出问题.

昨天我升级之后, 今天我的好多客户都说时间有问题,少了8个小时.

golang version: **such as 1.16**

carbon version: **such as 1.5.0**

time zone: **such as Shanghai**

go.mongodb.org/mongo-driver v1.10.1

**Comment by gouguoyin** [comment]
Sorry, I will consider a better implementation.
