### ISSUE TITLE
How to convert a time zone such as UTC/GMT +0800 to carbon's time zone name

### ISSUE THREAD

**Issue by whichdew** [golang-module/carbon#151]

**Comment by gouguoyin** [comment]
Please give an example

**Comment by whichdew** [comment]
> Please give an example
I want to achieve:

```go
now:=time.Now() //UTC +08:00 2022-08-19 01:00:00
dt:=carbon.CreateDateTime(now.Unix(),"UTC +09:30")
fmt.Println(dt) // expect 2022-08-19 02:30:00
```

**Comment by gouguoyin** [comment]
There are two ways：
1、By querying the [time zone table](https://blog.csdn.net/u012842630/article/details/105153463?share_token=80770415-9120-48ff-aa67-b5043defbb7c), we can see that Darwin is in this time zone
<img width="962" alt="image" src="https://user-images.githubusercontent.com/13517412/185732226-7d2ab86a-444f-47e2-a29e-905725c1e0f0.png">
```go
carbon.Now(carbon.Darwin).ToDateTimeString()
```
2、Use `time.FixedZone`
```go
location := time.FixedZone("UTC+9:30", +34200) // 9.5*60*60=34200
carbon.Now().SetLocation(location).ToDateTimeString()
```
The second way is recommended
