### ISSUE TITLE
Can you add the function of judging whether it is a legal holiday, regardless of the situation of adjustment

### ISSUE THREAD

**Issue by canuran** [golang-module/carbon#152]
法定节日调休虽然不确定，但哪些节日一定放假是确定的
比如5.1当天一定放假，中秋当天一定放假，10.1~10.7一定放假，农历正月初一至初七一定放假

**Comment by open-git** [comment]
You can extend the function yourself

**Comment by gouguoyin** [comment]
You can extend the function yourself.
