### ISSUE TITLE
add sequence generation

### ISSUE THREAD

**Issue by tjayrush** [golang-module/carbon#156]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

It would be nice if I could write something like carbon.Sequence("sunday", "2:00pm", 12) to produce twenty repetitions of Sunday at 2:00pm (or similar, of course).

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

I would use this to generate dates for some blockchain related software I'm working on that would then query for the block numbers at the given dates. In this way, i could generate account balances and do something akin to weekly profit and loss statements on my accounts.

**Comment by gouguoyin** [comment]
Please give an example of what is the return result of  `carbon.Sequence ("Sunday", "2:00pm", 12)`
