### ISSUE TITLE
New user experience - method naming

### ISSUE THREAD

**Issue by andig** [golang-module/carbon#162]
Thank you very much for this library! I came here from https://github.com/jinzhu/now and found many functions I was missing. 

I'd like to share what made the start difficult for me- naming. The naming convention could imho be more consistent and go-ish. Please allow me to make three breaking suggestions which would imho increase consistency and usability:

- `carbon.Time2Carbon` stutters- `carbon.FromTime` seems to be the natural name
- same reverse- `c.ToTime` instead of the odd `c.Carbon2Time` (why repeat the `Carbon` when you already have a carbon instance or us `2` when other functions use `To`?)
- all `carbon.CreateXxx` could become `carbon.Xxx` wich is a little less verbose

**Comment by gouguoyin** [comment]
Thank you for your feedback. Here is the reply to your feedback.

**Comment by gouguoyin** [comment]
For the naming of `carbon.CreateFromXxx`, I have referred to the naming rules of other languages such as 
php's [carbon](https://github.com/briannesbitt/Carbon)
<img width="846" alt="image" src="https://user-images.githubusercontent.com/13517412/209898896-c3151461-b7c9-454a-afbc-4e037f4c720c.png">
In addition, in terms of syntax, `carbon.CreateFromXxx` is more legal than `carbon.FromXxx`

**Comment by gouguoyin** [comment]
`Carbon.Carbon2Time()` is not named `carbon.FromTime()`  to avoid ambiguity with `carbon.CreateFromTime()` 

`Carbon.Time2Carbon()` is not named `carbon.ToTime()`  to avoid ambiguity with `carbon.ToTimeString()` and `carbon. Time()`

In addition,`Carbon2Time` or `Time2Carbon` is the conversion between two different structures of carbon and golang time. It is inappropriate to use `fromTime` or `toTime`

**Comment by gouguoyin** [comment]
If  `carbon.CreateFromXxx` is renamed as `carbon.FromXxx`, `carbon.ParseByXxx` is renamed as `carbon.ByXxx` ?

**Comment by andig** [comment]
I did not mean to imply that the naming is wrong or not consistent with the carbon ancestry. What I was trying to say is that it feels alien for me as a somewhat experienced Go developer. Your milage may vary of course.

> Carbon.Carbon2Time is not named carbon.FromTime to avoid ambiguity with carbon.CreateFromTime

All `Create` methods assemble a time. `FromTime` would be a straight conversion between both types.

> Carbon.Time2Carbon is not named carbon.ToTime to avoid ambiguity with carbon.ToTimeString and carbon.Time

I meant to suggest `carbon.FromTime`. The idiomatic way in Go to convert to string seems to be `String()`. With different formats probably `TimeString()` etc. I've not found examples of prefixing those with `To`.

> I don't think it is appropriate to use Carbon.FromTime or Carbon.ToTime

It would take away the "stuttering" which is a comment that regularly appears in Go repo's issue discussion.

All that said, no need to change anything. I was just sharing my experience, happy to have this issue closed if you want.

**Comment by gouguoyin** [comment]
Thanks for sharing your experience, the naming of functions is really a headache, maybe GPT-AI can solve this problem in the future.

**Comment by gouguoyin** [comment]
If possible, help me check whether the German translation resources [de.json](https://github.com/golang-module/carbon/blob/master/lang/de.json) are correct.

**Comment by andig** [comment]
Depending on context `now` is `jetzt`. `gerade eben` is the moment that has just passed while `jetzt` is `now`.

**Comment by gouguoyin** [comment]
> LGTM. Depending on context `now` is `jetzt`. `gerade eben` is the moment that has just passed while `jetzt` is `now`. Both may be valid:
> 
> * it has happened just now `gerade eben`
> * it is happening right now `jetzt`

Thank you very much, can you create a pr for [de.json](https://github.com/golang-module/carbon/blob/master/lang/de.json)?

**Comment by gouguoyin** [comment]
`v2.2.3` released and added `FromStdTime` alias method of `Time2Carbon` method and `ToStdTime` alias method of `Carbon2Time` method, `Time2Carbon` and `Carbon2Time` will be removed in the future
