### ISSUE TITLE
Whether to support carbon.SetTestNow?

### ISSUE THREAD

**Issue by hwbrzzl** [golang-module/carbon#166]
We can use `carbon.SetTestNow` to test some future features, just like([Link](https://github.com/briannesbitt/Carbon)):
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/24771476/222939956-a4378d91-acb6-4bef-be02-d3222b891648.png">

**Comment by gouguoyin** [comment]
Under planning

**Comment by gouguoyin** [comment]
Supported in version 2.2.5

**Comment by hwbrzzl** [comment]
Great job 👍
