### ISSUE TITLE
Format error

### ISSUE THREAD

**Issue by haowaiwai** [golang-module/carbon#168]
begin := carbon.Parse("2022-01-01 00:00:01")
fmt.Println(d.Format("y-W")) /22-52
Why not 22-01,thanks

**Comment by gouguoyin** [comment]
I will take some time to take a look

**Comment by limingxinleo** [comment]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/16648551/236667782-8b1aeb4f-25ae-4f27-9c8d-3a7b6efe9d36.png">


应该是正常的，第几周理论上都是算周一吧，周一还是 2021-12 月，所以是 52，只不过跟 年 配合起来，会显得很奇怪
