### ISSUE TITLE
Persian calendar

### ISSUE THREAD

**Issue by alirezaalizade025** [golang-module/carbon#169]
support persian calender

**Comment by gouguoyin** [comment]
what?

**Comment by alirezaalizade025** [comment]
please support Jalali calendar in your package,  see [ https://en.wikipedia.org/wiki/Iranian_calendars](url)

**Comment by gouguoyin** [comment]
I will consider it.

**Comment by MohammadGhodsian** [comment]
This repo may help (Solar Hijri calendar):
https://github.com/yaa110/go-persian-calendar

**Comment by gouguoyin** [comment]
v2.3.8 is supported and has been released
https://github.com/golang-module/carbon/tree/master/calendar/persian
