### ISSUE TITLE
Loss of precision when time is hour on the hour

### ISSUE THREAD

**Issue by devhaozi** [golang-module/carbon#171]
Hello,

I encountered an issue with the following code:
```go
carbon.SetTimezone(carbon.UTC).Now().StartOfDay().ToRfc3339MilliString()
```

golang version: 1.20

carbon version: 2.2.3

time zone: UTC

I expected to get:

```
2023-05-26T00:00:00.000Z
```

But I actually get:

```
2023-05-26T00:00:00Z
```

Thanks!

**Comment by gouguoyin** [comment]
When milliseconds are 0, the number after the decimal point is not displayed.
