### ISSUE TITLE
xorm combines carbon to write creation time? How to write it?

### ISSUE THREAD

**Issue by yoorxee** [golang-module/carbon#183]
数据表结构体是这样的
`CreatedAt          carbon.Time     `json:"created_at"``

carbon.Time 我再insert的时候，怎么写一个当前时间的carbon.Time类型？ 怎么写呢？

**Comment by gouguoyin** [comment]
Under what circumstances should only hours, minutes and seconds be stored?

**Comment by gouguoyin** [comment]
v2.2.8 added `Time`  struct and `ToTimeStruct` method
