### ISSUE TITLE
Are you too hasty with devastating updates and releases? ?

### ISSUE THREAD

**Issue by shuqingzai** [golang-module/carbon#186]
在 [v2.2.8 与 v2.2.9](https://github.com/golang-module/carbon/compare/v2.2.8...v2.2.9) 的更新中，CarbonDateTimeXXX 相关类型不再是把 Carbon 内嵌在其结构体中，而是重新定义类型，导致 `Carbon` 本身的方法不再适用于  CarbonDateTimeXXX 相关类型，这是毁灭性更新，代码直接无法编译的，我觉得这应该是一个 v2.3 甚至 v3 的版本，而不是一个BUG修复版本

参考下图，这些不方法不再可用

<img width="723" alt="image" src="https://github.com/golang-module/carbon/assets/44406033/05ec82d9-ac3b-4541-879b-115f85353800">

**Comment by gouguoyin** [comment]
Sorry, it was a bit hasty. I will urgently release a recovery version, and destructive updates will be released in v3.

**Comment by gouguoyin** [comment]
V2.2.10 has been released
