### ISSUE TITLE
What is the best way to mock carbon in unit testing?

### ISSUE THREAD

**Issue by matt9mg** [golang-module/carbon#195]
Hi,

I'm wondering what the best way to mock carbon as I cannot see an interface to aid with testing a custom service.

Thanks,

**Comment by gouguoyin** [comment]
https://github.com/golang-module/carbon#testing

**Comment by matt9mg** [comment]
oh nice thank you, I have a separate question say I was to inject carbon into a service struct i.e.

```go
func main() {
  lang := carbon.NewLanguage()
  lang.SetResources(map[string]string{
  "before": "Expires in %s",
  "after":  "Expired %s ago",
  })
  
  c := carbon.SetLanguage(lang)

ms := services.NewMyService(&c)
diff := ms.FromNowHumanReadable(...)
}
```

```go
type MysServiceInterface interface {
   FromNowHumanReadable(date time.time) string
}

type MyService struct {
   c *carbon.Carbon
}

func NewMyService(c *carbon.Carbon) MysServiceInterface {
   return &MyService{
      c: c,
   }
}

func (d *Date) FromNowHumanReadable(date time.Time) string {
	endDate := d.carbon.CreateFromTimestamp(date.Unix())

	return d.carbon.Now().DiffForHumans(endDate)
}
```

In this scenario, i have a wrapper helper to always get the diff from now, how do I mock carbon in a case where I have a single language which will save having to append the language string each call.

**Comment by gouguoyin** [comment]
Language locale must be set when rewriting some translation resources，if rewriting all resources, it is not necessary.
```go
lang := carbon.NewLanguage()
lang.SetLocale("en")
lang.SetResources(map[string]string{
    "before": "Expires in %s",
    "after":  "Expired %s ago",
})
```

**Comment by fikurimax** [comment]
Can't I mock the time in different package?

I'm testing web request in the main package (where I called carbon.SetTestNow), the handler is in different package (where I called carbon.Now()). But the time is not mocked when I use carbon.SetTestNow(carbon.CreateFromTime(23,59,58))

**Comment by fikurimax** [comment]
I am testing a web service and trying to mock the time using .SetTestNow() but in the handler/controller the time is not mocked

**Comment by gouguoyin** [comment]
> I am testing a web service and trying to mock the time using .SetTestNow() but in the handler/controller the time is not mocked

Show sample code.

**Comment by fikurimax** [comment]
![image](https://github.com/golang-module/carbon/assets/22553395/a397a8ee-6f42-4103-9a41-0404fe86a0c2)
The handler lives in different package than the test file

**Comment by gouguoyin** [comment]
> ![image](https://user-images.githubusercontent.com/22553395/285132095-a397a8ee-6f42-4103-9a41-0404fe86a0c2.png) The handler lives in different package than the test file

Carbon is not a pointer, so after `SetTestNow`, the value of carbon cannot be changed.

**Comment by gouguoyin** [comment]
```go
c := carbon.SetTimezone(carbon.UTC)

c.Now().ToDateString() // 2023-12-27
c.IsSetTestNow() // false

c.SetTestNow(carbon.Parse("2020-08-05"))
c.Now().ToDateString() // 2020-08-05
c.Now().IsSetTestNow() // true

c.UnSetTestNow()
c.Now().ToDateString() // 2023-12-2
c.Now().IsSetTestNow() // false
```

**Comment by fikurimax** [comment]
I thought we could do globally without creating an object like
```
carbon.SetTestNow(carbon.Parse("2020-12-12"))
```

And wherever i called
```
carbon.Now()
```
It'll give 2020-12-12
