### ISSUE TITLE
咨询关于Now函数入参的问题(About the Now function parameter issue)

### ISSUE THREAD

**Issue by maliyan** [golang-module/carbon#199]
`Now`函数的参数个数是可变数量的，但是，看`Carbon.Now`的实现，却是取最后一个值，这样定义的函数，对于调用者来说会不会产生误解？我的问题是，为什么要将参数定义成可变参数呢？
The number of parameters for the Now function is variable; however, in the implementation of Carbon.Now, it only takes the last value. Won't such a definition of the function lead to misunderstandings for the caller? My question is, why are the parameters defined as variable?
``` go
// Now returns a Carbon instance for now.
// 当前
func (c Carbon) Now(timezone ...string) Carbon {
	if len(timezone) > 0 {
		c.loc, c.Error = getLocationByTimezone(timezone[len(timezone)-1])
	}
....
}
```

**Comment by gouguoyin** [comment]
In `Now` method, the time zone is not mandatory and can also be set through `SetTimezone` method
