### ISSUE TITLE
IsLastDay,IsFirstDay方法不正确

### ISSUE THREAD

**Issue by almas1992** [golang-module/carbon#2]
- readme中`carbon := carbon:New()` 应该是` carbon := carbon.New()`。
- 源码中`IsLastDay`和`IsFisrtDay`方法复制`IsSunday`方法后忘了修改了

**Comment by gouguoyin** [comment]
感谢指正，isFirstDay和isLastDay方法确实写错了。
readme中carbon := carbon:New()&nbsp;应该是&nbsp;carbon := carbon.New()。我没看出有什么不同呀


---原始邮件---
发件人: "ALMAS"<notifications@github.com&gt;
发送时间: 2020年9月8日(周二) 晚上11:25
收件人: "golang-module/carbon"<carbon@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [golang-module/carbon] IsLastDay,IsFirstDay方法不正确 (#2)




  
readme中carbon := carbon:New() 应该是 carbon := carbon.New()。 

源码中IsLastDay和IsFisrtDay方法复制IsSunday方法后忘了修改了

**Comment by almas1992** [comment]
carbon点New()，不是carbon冒号New()

**Comment by gouguoyin** [comment]
> carbon点New()，不是carbon冒号New()

感谢指正

**Comment by gouguoyin** [comment]
> carbon点New()，不是carbon冒号New()

感谢指正

**Comment by gouguoyin** [comment]
已修复
