### ISSUE TITLE
Rename the func such as `carbon.CreateFromDate()`.

### ISSUE THREAD

**Issue by tanqiangyes** [golang-module/carbon#205]
## Feature Request

**Is your feature request related to a problem? Please describe:**
When I use `carbon.CreateFromDate(2023,1,1)`, I think I will get the time `2023-01-01 00:00:00`, but actually I get the time `2023-01-01 Current Hour: Current Minutes: Current Seconds Current Nanoseconds`. I think this naming "CreateFromDate" is confusing and we should change it to something that describes its function more precisely, like " CreateFromDateUseCurrentHMS".

**Describe the feature you'd like:**
Rename the func such as `carbon.CreateFromDate()`.

**Describe alternatives you've considered:**
Yes, we can use `carbon.CreateFromDateTimeNano`，but for a new user, `CreateFromDate` is still disorienting, which will cause unexpected bugs in their work

**Teachability, Documentation, Adoption, Migration Strategy:**
With this renaming, users will know exactly what time they are using, and will not have a series of bugs caused by the use of this package, which can be implemented in a new version without affecting the old version of the code.

**Comment by gouguoyin** [comment]
Thank you for your feedback, I will seriously consider it.

**Comment by tanqiangyes** [comment]
If you don't want to change the name, then perhaps the notes should be written more clearly? Because as it stands now, the notes don't describe what the functions do very clearly.

**Comment by gouguoyin** [comment]
I also hesitated when I first named it, `CreateFromDate` is to be consistent with `CreateFromTime`, in `CreateFromTime`, the year, month, and day are taken from current time, so, all omitted values are taken to the current time.

**Comment by gouguoyin** [comment]
`2023-01-01 Current Hour: Current Minutes: Current Seconds Current Nanoseconds`? No `Current Nanoseconds`
<img width="849" alt="image" src="https://github.com/golang-module/carbon/assets/13517412/71abc955-bcfe-42e2-bb06-3280e8ee1cd0">

**Comment by tanqiangyes** [comment]
I know that I can also use `carbon.CreateFromDateTimeNano`. But the confusing nature of function names is still there.

**Comment by tanqiangyes** [comment]
![image](https://github.com/golang-module/carbon/assets/25723492/c4ae4e29-6c95-48c9-b57b-d96efe499d1d)
Nanoseconds exist in your concrete realization.

> `2023-01-01 Current Hour: Current Minutes: Current Seconds Current Nanoseconds`? No `Current Nanoseconds` <img alt="image" width="849" src="https://private-user-images.githubusercontent.com/13517412/287983928-71abc955-bcfe-42e2-bb06-3280e8ee1cd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjkxODQsIm5iZiI6MTcwMTc2ODg4NCwicGF0aCI6Ii8xMzUxNzQxMi8yODc5ODM5MjgtNzFhYmM5NTUtYmNmZS00MmUyLWJiMDYtMzI4MGU4ZWUxY2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMTQ5NmViNjkzMTdjNzE2MWM1MWFjZmY4Yjk2ODdjYzMzMjc0NTkwYTA3NGY4M2E1YmI5ZDNiM2UwMmIzNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TrkUibCRfZ_h8Vp3Zfs6P92oHu29pr08meW8DI6IFDY">

**Comment by tanqiangyes** [comment]
> What should be the year, month and day in `CreateFromTime`? `0000-00-00` or `currentYear-currentMonth-currentDay`

`currentYear-currentMonth-currentDay` maybe this， but nobody can kown this from func name or func comment

**Comment by tanqiangyes** [comment]
> What should be the year, month and day in `CreateFromTime`? `0000-00-00` or `currentYear-currentMonth-currentDay`
As you said, is it 0000-00-00 or currentYear-currentMonth-currentDay which is unknown to the user?

**Comment by gouguoyin** [comment]
Optimized in v2.3.0
<img width="817" alt="image" src="https://github.com/golang-module/carbon/assets/13517412/6742ffea-1c51-4452-a29c-301f637fd624">
