### ISSUE TITLE
希望加入时间比较功能

### ISSUE THREAD

**Issue by BrettCao** [golang-module/carbon#21]
实现类似于：几小时前 几分钟前 这样的功能 
希望越做越好！

**Comment by gouguoyin** [comment]
已在考虑中，目前主要纠结是返回英文还是中文，还是统一规划i18n国际化支持

**Comment by gouguoyin** [comment]
> 实现类似于：几小时前 几分钟前 这样的功能
> 希望越做越好！

已在考虑中，目前主要纠结是返回英文还是中文，还是统一规划i18n国际化支持

**Comment by BrettCao** [comment]
> > 实现类似于：几小时前 几分钟前 这样的功能
> > 希望越做越好！
> 
> 已在考虑中，目前主要纠结是返回英文还是中文，还是统一规划i18n国际化支持

像carbon php 一样支持18国语言？

**Comment by gouguoyin** [comment]
> > > 实现类似于：几小时前 几分钟前 这样的功能
> > > 希望越做越好！
> > 
> > 
> > 已在考虑中，目前主要纠结是返回英文还是中文，还是统一规划i18n国际化支持
> 
> 像carbon php 一样支持18国语言？

对，有这种规划，用json文件存储翻译信息

**Comment by BrettCao** [comment]
> > > > 实现类似于：几小时前 几分钟前 这样的功能
> > > > 希望越做越好！
> > > 
> > > 
> > > 已在考虑中，目前主要纠结是返回英文还是中文，还是统一规划i18n国际化支持
> > 
> > 
> > 像carbon php 一样支持18国语言？
> 
> 对，有这种规划，用json文件存储翻译信息

期待！两个时间对比的功能很实用，特别是像社区这种

**Comment by mingzaily** [comment]
期待！
