### ISSUE TITLE
Default JSON template settings

### ISSUE THREAD

**Issue by shuqingzai** [golang-module/carbon#215]
目前 carbon 在序列化 JSON 或 Stringer 时，默认模板格式类似: `2024-01-05 13:10:11` 的格式，是否可以将默认模板格式定义为全局变量，让用户可以在项目启动时，全局设置默认模板格式，如：需要将默认格式恢复为 `2024-01-05T13:10:11+08:00`，虽然目前可以设置标签的方式更改，但是需要借助反射的能力，对性能而言还是有影响的，而且一般对于一个项目而言，时间格式基本都是固定，只需要设置一次就可以，后续如果特殊情况才启动 tag 的能力，而不是每个 carbon 字段都需要设置

**Comment by gouguoyin** [comment]
v2.3.4 is supported and has been released
```go
carbon.SetDefault(carbon.Default{
  Layout: carbon.RFC3339Layout,
  Timezone: carbon.PRC,
  Locale: "en",
})
```
