### ISSUE TITLE
Starting from v2.3.0, after removing the series of methods such as DateTime, it is extremely inconvenient to insert the birthday (Y-m-d) field with gorm now. What is the best practice

### ISSUE THREAD

**Issue by liaohongxing** [golang-module/carbon#217]
从v2.3.0开始 , 移除DateTime等系列方法后 ，全部改用 Carbon后，现在用gorm插入包含生日(Y-m-d)字段，前端传Y-m-d , 后台一直报 layout "2006-01-02 15:04:05" 错误 ，设置了carbon:"type:date" 依旧不行，同样的问题存在于查询一个列表的情况 ，似乎json序列化,反序列化，不会识别设置的Tag参数 ，极为不便，最佳实践是什么

**Comment by gouguoyin** [comment]
https://github.com/golang-module/carbon/blob/master/README.cn.md#json
<img width="676" alt="image" src="https://github.com/golang-module/carbon/assets/13517412/10919131-2a4a-4126-96a3-58d7a3b73bc2">

**Comment by gouguoyin** [comment]
建议在项目入口文件(如 `main.go`)里设置全局模板格式、时区等
```go
carbon.SetDefault(carbon.Default{
  Layout: carbon.RFC3339Layout,
  Timezone: carbon.PRC,
  WeekStartsAt: carbon.Sunday,
  Locale: "zh-CN",
})
```

**Comment by liaohongxing** [comment]
这个SetDefault 是很好的，但是略显鸡肋，部分非标准layout还是没有之前用起来顺畅，要是能解决json序列化，反序列能读取设置的非标准tag就好了

**Comment by gouguoyin** [comment]
> 这个SetDefault 是很好的，但是略显鸡肋，部分非标准layout还是没有之前用起来顺畅，要是能解决json序列化，反序列能读取设置的非标准tag就好了

之前是预置的固定类型，没有预置的就没办法处理，现在使用 `SetDefault` 把控制权交给了用户，`SetDefault` 可以设置任何标准或非标准的 `layout`

**Comment by gouguoyin** [comment]
如果要使用 `tag` 也可以，不过使用了泛型，性能会受到影响。使用 `tag` 序列化或者反序列化前必须调用 `carbon.loadTag` 方法载入 `tag`
<img width="462" alt="image" src="https://github.com/golang-module/carbon/assets/13517412/8a8ef108-dfb5-4382-80fc-c63062ce701f">

**Comment by gouguoyin** [comment]
总结起来
1、如果结构体里时间字段输出格式都一样，使用 `carbon.SetDefault`
2、如果结构体里时间字段输出格式不一样，使用 `tag` 配合 `carbon.LoadTag`
