### ISSUE TITLE
build for windows_386 (untyped int constant) overflows int

### ISSUE THREAD

**Issue by iTanken** [golang-module/carbon#219]
Hello,

I encountered an issue with the following code:

```go
github.com\golang-module\carbon\v2\calendar\lunar\lunar.go:161:31
```

golang version: **1.20.13**

carbon version: **2.3.6**

I expected to get:

```
exit status 0
```

But I actually get:

```
failed to build for windows_386: exit status 1: # github.com/golang-module/carbon/v2/calendar/lunar
vendor\github.com\golang-module\carbon\v2\calendar\lunar\lunar.go:161:31: -2206512000 (untyped int constant) overflows int

exit status 1
```

Thanks!

**Comment by gouguoyin** [comment]
failed when install？

**Comment by iTanken** [comment]
> failed when install？

when building 32-bit programs

**Comment by gouguoyin** [comment]
安装时没问题，交叉编译时出错吗？

**Comment by iTanken** [comment]
> 安装时没问题，交叉编译时出错吗？

嗯，64 位编译运行没有问题，设置 `GOARCH=386` 编译 32 位程序的时候 `lunar.go` 第 161 行 `int` 溢出。

v2.3.5 在 32位环境下是编译运行正常的。
