### ISSUE TITLE
期望ToTimestamp()可以加入微妙，纳秒输出

### ISSUE THREAD

**Issue by wingofsky** [golang-module/carbon#22]
期望ToTimestamp()可以加入微妙，纳秒输出

**Comment by gouguoyin** [comment]
> 期望ToTimestamp()可以加入微妙，纳秒输出

微妙、纳秒的使用场景多吗？

**Comment by wingofsky** [comment]
> > 期望ToTimestamp()可以加入微妙，纳秒输出
> 
> 微妙、纳秒的使用场景多吗？

微妙看对接方的需求，有时候后面加三个0就行，但有些爬虫场景会校验微妙；
纳秒倒是真不多

**Comment by open-git** [comment]
> > > 期望ToTimestamp()可以加入微妙，纳秒输出
> > 
> > 
> > 微妙、纳秒的使用场景多吗？
> 
> 微妙看对接方的需求，有时候后面加三个0就行，但有些爬虫场景会校验微妙；
> 纳秒倒是真不多

这种情况在时间戳的基础上乘以1000不就是毫秒了么？

**Comment by open-git** [comment]
> > > 期望ToTimestamp()可以加入微妙，纳秒输出
> > 
> > 
> > 微妙、纳秒的使用场景多吗？
> 
> 微妙看对接方的需求，有时候后面加三个0就行，但有些爬虫场景会校验微妙；
> 纳秒倒是真不多
在时间戳的基础上乘以1000000不就是微秒了么？

**Comment by wingofsky** [comment]
> > > > 期望ToTimestamp()可以加入微妙，纳秒输出
> > > 
> > > 
> > > 微妙、纳秒的使用场景多吗？
> > 
> > 
> > 微妙看对接方的需求，有时候后面加三个0就行，但有些爬虫场景会校验微妙；
> > 纳秒倒是真不多
> > 在时间戳的基础上乘以1000000不就是微秒了么？

格式是对了，但值有滑点

**Comment by gouguoyin** [comment]
v1.2.3版本已支持毫秒、微妙和纳秒级时间戳输出，具体查看ToTimestampWithMicrosecond()、ToTimestampWithMillisecond()、ToTimestampWithNanosecond()方法
