### ISSUE TITLE
cannot parse string null

### ISSUE THREAD

**Issue by a8ss** [golang-module/carbon#225]
```go
import ("github.com/golang-module/carbon/v2")
type Person struct {
	Field1 string        `json:"field1,omitempty"`
	Field2 carbon.Carbon `json:"field2,omitempty" carbon:"omitempty"`
}
var p Person
err := json.Unmarshal([]byte("{\"field1\":null,\"field2\":null}"), &p)
fmt.Println(err, p)
```

> cannot parse string "null" as carbon by layout "2006-01-02 15:04:05", please make sure the value and layout match { } 

Add the omitempty tag to prevent parsing errors ?

**Comment by a8ss** [comment]
The responses of some APIs are null, and I have no control over them.

**Comment by gouguoyin** [comment]
<img width="445" alt="image" src="https://github.com/golang-module/carbon/assets/13517412/6f5096f6-e934-426a-b7ed-78fb788b86ff">
