### ISSUE TITLE
DiffAbsInDuration must upgrade go version to 1.9+

### ISSUE THREAD

**Issue by xu9374** [golang-module/carbon#226]
in [v2.3.9+](https://github.com/golang-module/carbon/releases/tag/v2.3.9) ，`DiffAbsInDuration` used `Duration.Abs()`，but this func must in go version 1.9+，see [api: audit for Go 1.19](https://github.com/golang/go/issues/53310) and [time: add Duration.Abs](https://github.com/golang/go/issues/51414)
if my go version is below 1.9, it will not compile successfully. report `github.com/golang-module/carbon/v2@v2.3.10/difference.go:212:40](http://github.com/golang-module/carbon/v2@v2.3.10/difference.go:212:40): end.StdTime().Sub(c.StdTime()).Abs undefined (type time.Duration has no field or method Abs)`
Do you need to update the documentation to explain that you need to use go 1.9+ after version 2.3.9+?

**Comment by gouguoyin** [comment]
Thank you for your feedback. I will pay attention to this issue

**Comment by gouguoyin** [comment]
The next version will implement `Abs` method by itself

**Comment by gouguoyin** [comment]
V2.3.11 has been optimized and released
