### ISSUE TITLE
Can you add the 1.5.5 tag?

### ISSUE THREAD

**Issue by zhoushun5678** [golang-module/carbon#227]
你好，我用到一个包里面有用到(github.com/golang-module/carbon v1.5.5)，能加上这个1.5.5版本吗？🤝

**Comment by gouguoyin** [comment]
Which package? v1.5.5 is too old, the API has been greatly changed.

**Comment by zhoushun5678** [comment]
At the end of last year, this version was still available, but not now. Can you help me get one?

**Comment by gouguoyin** [comment]
v1.5.5 branch code is gone and there is no way to tag it anymore.
