### ISSUE TITLE
Incorrect Parse of 0001-01-01 00:00:00

### ISSUE THREAD

**Issue by lesichkovm** [golang-module/carbon#232]
Hello,

I encountered an issue with the following code:
```go
0001-01-01 00:00:00 +0000 GMT
```

golang version: 1.22 (latest)

carbon version: 2.3.10 (latest)

time zone: GMT

I expected to get:

```
0001-01-01 00:00:00
```

But I actually get:

```
nothing
```

Example of issue: 
https://play.golang.com/p/L6HDUXlCDEz

How it is supposed to work: 
![image](https://github.com/golang-module/carbon/assets/7744963/e262df81-a4ed-4592-b975-0f7c51168d73)

Thanks!

**Comment by gouguoyin** [comment]
After testing, `0001-01-01 00:00:00+0000 GMT` is a zero value, but `0000-01-01 00:00:00+0000 GMT` or `0002-01-01 00:00:00+0000 GMT` is not

<img width="867" alt="image" src="https://github.com/golang-module/carbon/assets/13517412/2a0e9982-6864-43b0-99c6-4847428e52fa">

https://play.golang.com/p/Ozr7GaWc0sD

**Comment by lesichkovm** [comment]
This looks very wrong. According to AI:
```
"0000-01-01 00:00:00" is not a valid date according to the most common date and time  standards. Here's why: 
Year Zero Doesn't Exist: Our calendar system doesn't have a year zero. There was no year 0 between 1 BC and 1 AD.
```

**Comment by lesichkovm** [comment]
> After testing, in golang, `0001-01-01 00:00:00+0000 GMT` is a zero value, but `0000-01-01 00:00:00+0000 GMT` or `0002-01-01 00:00:00+0000 GMT` is not

Your tests will pass if you update the time layout:

https://play.golang.com/p/AUKnroJAxlj

**Comment by gouguoyin** [comment]
> > After testing, in golang, `0001-01-01 00:00:00+0000 GMT` is a zero value, but `0000-01-01 00:00:00+0000 GMT` or `0002-01-01 00:00:00+0000 GMT` is not
> 
> Your tests will pass if you update the time layout:
> 
> https://play.golang.com/p/AUKnroJAxlj

The layout does not match the time string，the layout contains a time zone, but the time string does not

**Comment by lesichkovm** [comment]
Sorted by using 0002-01-01 00:00:00 which is the earliest valid date

**Comment by gouguoyin** [comment]
V2.3.11 has been optimized and released
