### ISSUE TITLE
method: a.DiffInDuration(b)   is b-a !  This is not in line with intuition 

### ISSUE THREAD

**Issue by zhangdekui** [golang-module/carbon#239]
This is very easy to make mistakes... 
The following code is the standard library of golang:
	b := time.Date(2022, time.March, 10, 10, 0, 0, 0, time.UTC)
	a := time.Now()
        diff := a.Sub(b)
        fmt.Println(diff.Hours())

result is 20464.558380785, is a-b !

**Comment by gouguoyin** [comment]
The API has been determined and cannot be changed arbitrarily
