### ISSUE TITLE
时间戳没有毫秒的吗？

### ISSUE THREAD

**Issue by yaobo-lab** [golang-module/carbon#24]
时间戳没有毫秒的吗？
	c := carbon.Now().ToTimestamp()
	b := time.Now().UnixNano() / int64(time.Millisecond)

1603956642
1603956642535

**Comment by gouguoyin** [comment]
> 1603956642535

下个版本我再加一个获取毫秒时间戳的方法吧

**Comment by gouguoyin** [comment]
v1.2.3版本已支持毫秒、微妙和纳秒级时间戳输出，具体查看ToTimestampWithMicrosecond()、ToTimestampWithMillisecond()、ToTimestampWithNanosecond()方法
