### ISSUE TITLE
json null value

### ISSUE THREAD

**Issue by a8ss** [golang-module/carbon#240]
Hello,

I encountered an issue with the following code:
```go
c := struct {
    ActiveTime carbon.TimestampMilli `json:"activeTimeStamp"`
}{}

err := json.Unmarshal([]byte(`{"activeTimeStamp":null}`), &c)
fmt.Println(c.ActiveTime, c.ActiveTime.IsValid(), c.ActiveTime.IsZero(), err)
```

golang version: **such as 1.21**

carbon version: **such as 2.3.12**

I expected to get:

```
0 false true <nill>
```

But I actually get:

```
0 true false <nil>
```

Thanks!

**Comment by gouguoyin** [comment]
v2.4.1 has been fixed and released https://github.com/golang-module/carbon/blob/e3a062b142b3b57c83d06ba3e2079e9e0918a3ea/encoding_unit_test.go#L396
