### ISSUE TITLE
different timezone，return the same string

### ISSUE THREAD

**Issue by WashCai** [golang-module/carbon#241]
```golang
        GmtNow := carbon.SetTimezone(carbon.GMT).Now()
	CstNow := carbon.SetTimezone(carbon.PRC).Now()

	fmt.Println(GmtNow)
	fmt.Println(CstNow)
```
`GmtNow` and `CstNow` is the same.
carbon version is v2.3.12

How can I get the different time?

**Comment by gouguoyin** [comment]
```go
fmt.Println(GmtNow.ToDateTimeString())
fmt.Println(CstNow.ToDateTimeString())
```

**Comment by WashCai** [comment]
> ```go
> fmt.Println(GmtNow.ToDateTimeString())
> fmt.Println(CstNow.ToDateTimeString())
> ```

Same again.
I change the version to v2.2.3 and it work
at v2.3.12 It work like
```go
fmt.Println(GmtNow.Format("Y-m-d H:i:s"))
fmt.Println(CstNow.Format("Y-m-d H:i:s"))
```

 I think this is a bug

**Comment by gouguoyin** [comment]
v2.4.0 has been fixed and released
