### ISSUE TITLE
建议增加一些比较方法

### ISSUE THREAD

**Issue by ib1ack** [golang-module/carbon#25]
建议增加：
1.是否相等
2.是否不等
3.是否在之后
4.是否在之前
5.是否在两个时间中间
虽然通过现有的比较方法也能实现上述的功能，还是希望大佬能封装一下

**Comment by gouguoyin** [comment]
> 建议增加：
> 1.是否相等
> 2.是否不等
> 3.是否在之后
> 4.是否在之前
> 5.是否在两个时间中间
> 虽然通过现有的比较方法也能实现上述的功能，还是希望大佬能封装一下

下个版本会增加

**Comment by ib1ack** [comment]
> > 建议增加：
> > 1.是否相等
> > 2.是否不等
> > 3.是否在之后
> > 4.是否在之前
> > 5.是否在两个时间中间
> > 虽然通过现有的比较方法也能实现上述的功能，还是希望大佬能封装一下
> 
> 下个版本会增加

v5

**Comment by BrettCao** [comment]
类似于carbonperiod的实现，可以独立出来

**Comment by gouguoyin** [comment]
v1.2.4版本已新增新增Compare()、Gt()、Lt()、Between()、BetweenIncludedStartTime()等多个方法，详情请查看 [文档](https://github.com/golang-module/carbon#%E6%97%B6%E9%97%B4%E6%AF%94%E8%BE%83)
