### ISSUE TITLE
建议增加是否解析出错的 api

### ISSUE THREAD

**Issue by eyasliu** [golang-module/carbon#28]
现在一旦解析时间出错，[直接panic](https://github.com/golang-module/carbon/blob/master/private.go#L48)，这是不是太暴力了，一旦没处理好直接导致程序奔溃，建议增加api让使用者可以判断是否解析出错了，比如

```
var isError bool = carbon.Parse("2020-11-11 123").IsError()

// 或者像Gorm那样
var err error = carbon.Parse("2020-11-11 123").Error
```

解析出错直接 panic 真的很不好处理，除了在 defer 去消化就没其他方法了

**Comment by gouguoyin** [comment]
> 现在一旦解析时间出错，[直接panic](https://github.com/golang-module/carbon/blob/master/private.go#L48)，这是不是太暴力了，一旦没处理好直接导致程序奔溃，建议增加api让使用者可以判断是否解析出错了，比如
> 
> ```
> var isError bool = carbon.Parse("2020-11-11 123").IsError()
> 
> // 或者像Gorm那样
> var err error = carbon.Parse("2020-11-11 123").Error
> ```
> 
> 解析出错直接 panic 真的很不好处理，除了在 defer 去消化就没其他方法了

我考虑下

**Comment by WilliamYang1992** [comment]
要改也是这样吧，_, err := carbon.Parse("")

**Comment by eyasliu** [comment]
> 要改也是这样吧，_, err := carbon.Parse("")

这样就对原本API有变动了，会造成不兼容的

**Comment by del-xiong** [comment]
我觉得可以这样修改
```
func Parse(args ...interface{}) Carbon {
	timeString := args[0].(string)
	ParseError := errors.New("parse error: ....")
	// if error occured
	if (len(args) > 1 && fmt.Sprintf("%T", args[1]) == "*error") {
		reflect.ValueOf(args[1]).Elem().Set(reflect.ValueOf(ParseError))
		return Carbon{loc: getLocalByTimezone(Local)}
	}
	// ...

}

	var err error
	result := Parse("2020-11-11 123", &err)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("parse result: %s \n", result)

```

这样就又能自己处理error又不影响之前的流程了

第三方非核心库确实不应该panic ，会导致生产问题，应该交给用户自己决定

**Comment by gouguoyin** [comment]
我更倾向于给carbon增加Error字段，如
`if err := carbon.Parse("2020-11-11 123").Error; err != nil {
    // 错误处理...
}`

**Comment by WilliamYang1992** [comment]
不兼容就不兼容吧，用 .Error 不符合 golang 一般的编码风格

参考其它库，会这样设置的，有两个方法
_, err := Parse()
_  = MustParse()

用哪个取决于用户

**Comment by eyasliu** [comment]
@WilliamYang1992 常规做法是这样子，`Must*` 一旦出错就会 panic，按照这种风格就必需改动现有 API 了，这对于上百 star 的开源项目做那么大的 api 变动可不是好事。考虑参考 gin 的api，`ShouldParse` 的时候不panic，或者参考 gorm 加 Error 字段

**Comment by del-xiong** [comment]
要兼容只能加api
result := Parse()
err,result := SafeParse()

按一般的习惯是Parse抛err， MustParse强制转

**Comment by gouguoyin** [comment]
经过慎重考虑，决定采用`if err := carbon.Parse("2020-11-11 123").Error; err != nil { // 错误处理... }`这种方式来处理错误，详情请查看[readme.md](https://github.com/golang-module/carbon/#%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86)，欢迎大家提出宝贵意见
