### ISSUE TITLE
[Feature Request]add method to convert to time.Time

### ISSUE THREAD

**Issue by leopku** [golang-module/carbon#31]
In somecase,  I need convert carbon object to time.Time.
Currently, I need convert carbon to timestamp and then convert to time.Time
For example a database model defined in **legacy** project as below,

```go

type Post struct {
  ID string
  CreatedAt null.Time
  UpdatedAt null.Time
  ...
}


post := Post{}
c := carbon.Now()
timestamp := c.ToTimestamp()
post.CreatedAt = null.FromTime(time.Unix(timestamp))
...
```
If there are many time fields in Post struct, it's boring to do the converting manually on each field.

But it would be clean like this
```go
post.CreatedAt = null.FromTime(carbon.Now().ToTimeDotTime())
```

It's much appreciate if this awesome project add a method to get time.Time.

**Comment by gouguoyin** [comment]
carbon.CreateFromGoTime(time.Now())

**Comment by leopku** [comment]
I had found `ToTimestamp()` method as described above.
The problem is I need convert manually on each time fields.
Is there any way to get `time.Time` directly or why not provide a way to convert to time.Time? 

BTW, `null.FromTime()` need a `time.Time` but not timestamp as params .

**Comment by gouguoyin** [comment]
中文沟通吧

**Comment by leopku** [comment]
能加个方法直接从 carbon 转换到 time.Time 吗？
有些场景需要 time.Time 入参。

现在虽然可以通过 timestamp 转换，但是如果库就自带了这个方法，使用起来不是更方便吗，你说呢？

**Comment by leopku** [comment]
其实代码就两行，如果需要的话，我可以提 PR。
就是方法取啥没想好。

**Comment by gouguoyin** [comment]
可以看下carbon.go源码，
`type Carbon struct {
	Time time.Time
	loc  *time.Location
}`
carbon.Now().Time就是time.Time类型

**Comment by leopku** [comment]
Got it.
Thanks.
