### ISSUE TITLE
BUG: EndOfWeek may go to the next week when it is sunday!

### ISSUE THREAD

**Issue by iflamed** [golang-module/carbon#32]
now := sunday()
now.EndOfWeek() will be the next week's end time.

**Comment by gouguoyin** [comment]
now := sunday()是什么语法？
经单元测试，没有发现此问题。具体可以看carbon_test.go文件TestCarbon_EndOfWeek里输入2020-10-04(周日)，经过EndOfWeek处理后是2020-10-04 23:59:59，并未跨周。
![image](https://user-images.githubusercontent.com/13517412/104847725-d6a49a00-591c-11eb-8114-60227c096995.png)
