### ISSUE TITLE
希望添加农历操作

### ISSUE THREAD

**Issue by coder2z** [golang-module/carbon#35]
希望添加农历操作

**Comment by myxy99** [comment]
农历日期 与 阳历日期转换

**Comment by gouguoyin** [comment]
后续会增加，目前还是以基础功能完善为主

**Comment by gouguoyin** [comment]
> 农历日期 与 阳历日期转换

阴历和阳历直接的转换吧？

**Comment by coder2m** [comment]
就比如 今天 阴历输出为->20210118

**Comment by coder2m** [comment]
输入对应的 农历 输出 阳历 ：比如 in：20210118 => out：20210301

**Comment by RickieL** [comment]
最近用了一下那个lunar输出，发现都是一样的内容，农历十一月廿五日。
看代码，原来还是todo状态，这块有后续的完善计划么。

**Comment by gouguoyin** [comment]
> 最近用了一下那个lunar输出，发现都是一样的内容，农历十一月廿五日。
> 看代码，原来还是todo状态，这块有后续的完善计划么。

有后续完善计划

**Comment by RickieL** [comment]
大概什么时候可用哦

**Comment by gouguoyin** [comment]
v1.4.1版本已支持农历，详情请查看 https://gitee.com/go-package/carbon/tree/v1.4.1#%E5%86%9C%E5%8E%86

**Comment by hyahm** [comment]
请问农历怎么转阳历
