### ISSUE TITLE
结构体函数于接口

### ISSUE THREAD

**Issue by luanruisong** [golang-module/carbon#36]
建议所有对外输出采用接口的形式，而不是struct函数直接硬撸，这样可以有效解耦并提高可扩展性

**Comment by gouguoyin** [comment]
能具体举些例子么

**Comment by luanruisong** [comment]
https://github.com/luanruisong/g-steam/blob/main/client.go

**Comment by luanruisong** [comment]
可以参考一下

**Comment by jxlwqq** [comment]
@luanruisong 

func NewClient(appKey string) *Client {} // 那也是返回 *Client，而不是 *client

**Comment by luanruisong** [comment]
是的。。写错了  返回Client即可
