### ISSUE TITLE
Yesterday, Tomorrow 方法是否可以调整？

### ISSUE THREAD

**Issue by WilliamYang1992** [golang-module/carbon#38]
![image](https://user-images.githubusercontent.com/19986480/106096688-ff286180-6170-11eb-9f5b-ef56c37663c4.png)

一开始用，我以为方法 c.Yesterday() 跟 函数 carbon.Yesterday() 是不一样的，现在感到比较迷惑

为什么不这样呢？
carbon.Yesterday() 返回今天的昨天
c.Yesterday() 返回某一天的昨天

**Comment by gouguoyin** [comment]
carbon.SetTimezone(PRC).Yesterday() 该返回哪一天的昨天？

**Comment by WilliamYang1992** [comment]
不明白你上面这条语句是什么意思，我理解应该返回调整时区的那个时间的昨天
例如，今天凌晨3点时，昨天是27日，对美国人来说，那时候的昨天是26日

**Comment by gouguoyin** [comment]
你说的c.Yesterday() 返回某一天的昨天，但是如果并没有指定某一天的话该返回哪天的昨天。理论上
carbon.SetTimezone(PRC).Yesterday()和carbon.Yesterday()不就应该是一样的么？

**Comment by WilliamYang1992** [comment]
我明白你的意思了，如果没有指定时间，那么你的c.Time.IsZero 就为 True了，能否用这个来判断？没有指定时间就用time.Now(）来计算？有值的就用该时间操作，这样会有别的问题吗？

**Comment by gouguoyin** [comment]
这样可以，下个版本处理这个问题。

**Comment by gouguoyin** [comment]
假设今天是2010-01-28，那么carbon("2010-01-31").Yesterday().IsYesterday()应该是true还是false?IsYesterday()只能基于当前时间来判断吧

**Comment by WilliamYang1992** [comment]
这个只能是用当前时间去比较，所以是返回false&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gouguoyin <notifications@github.com&gt;
发送时间: 2021年1月28日 16:48
收件人: golang-module/carbon <carbon@noreply.github.com&gt;
抄送: William Yang <505741310@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[golang-module/carbon] Yesterday, Tomorrow 方法是否可以调整？ (#38)





 
假设今天是2010-01-28，那么carbon("2010-01-31").Yesterday().IsYesterday()应该是true还是false?IsYesterday()只能基于当前时间来判断吧

**Comment by gouguoyin** [comment]
v1.2.7已发布，优化Yesterday()和tomorrow()方法，Format()方法增加对N、L、G、U、O、P、T等格式化符号支持
