### ISSUE TITLE
 invalid locale "zh-CN", please see the lang directory for all valid locale

### ISSUE THREAD

**Issue by zhifeifu** [golang-module/carbon#41]
包版本:1.3.3
使用示例代码:
```
	c := carbon.Now().AddHours(1).SetLocale("zh-CN")
	if c.Error != nil {
		// 错误处理
		log.Fatal(c.Error)
	}
	// 狮子座
	fmt.Println(c.Constellation())
```

**Comment by gouguoyin** [comment]
本地测试没有问题
![image](https://user-images.githubusercontent.com/13517412/109473221-feefee80-7aad-11eb-84f2-b36b2096398e.png)

![image](https://user-images.githubusercontent.com/13517412/109473191-f5668680-7aad-11eb-9141-9134c28ea25a.png)

**Comment by gouguoyin** [comment]
找到原因了，是因为作为第三方包使用时不能直接读取子目录里的json文件，正在修复，你可以暂时把lang目录复制到当前项目下就可以正常使用了

**Comment by gouguoyin** [comment]
v1.3.4版本发布了
