### ISSUE TITLE
紧急问题，Format方法失效

### ISSUE THREAD

**Issue by da4z** [golang-module/carbon#42]
Format方法返回空字符串 ，系统全崩 。

```go
package main

import (
	"fmt"

	"github.com/golang-module/carbon"
)

func main() {
	s := carbon.Now().Format("Y-m-d H:i:s")
	fmt.Println("==============", s)
}
```

**Comment by gouguoyin** [comment]
![image](https://user-images.githubusercontent.com/13517412/109583710-4c666d00-7b3b-11eb-9d53-6c380a7f78fd.png)
![image](https://user-images.githubusercontent.com/13517412/109583745-5ab48900-7b3b-11eb-86d8-5a08a4b78313.png)

**Comment by chinaapus** [comment]
![Uploading 企业微信截图_20210302103614.png…]()

**Comment by chinaapus** [comment]
我该用什么代码能跟您环境一样 。
version: v1.3.3
golang: v1.16

**Comment by gouguoyin** [comment]
找到原因了，是因为作为第三方包使用时不能直接读取子目录里的json文件，正在修复，你可以暂时把lang目录复制到当前项目下就可以正常使用了

**Comment by gouguoyin** [comment]
v1.3.4版本已修复
