### ISSUE TITLE
carbon.Parse("2019-08-05 13:14:15").DiffForHumans() 

### ISSUE THREAD

**Issue by wanminny** [golang-module/carbon#43]
carbon.Parse("2019-08-05 13:14:15").DiffForHumans() 
是空？？

**Comment by gouguoyin** [comment]
使用涉及到多语言的方法需要把lang目录复制到项目目录下

**Comment by gouguoyin** [comment]
![image](https://user-images.githubusercontent.com/13517412/109760045-012a8800-7c29-11eb-963c-5cad4cf33e71.png)
后续版本会利用golang1.16官方内置静态资源嵌入方案embed来解决，目前先把lang目录复制到项目目录下即可正常使用。

**Comment by wanminny** [comment]
ok thx,it's worked!

**Comment by wanminny** [comment]
这样关机的信息建议还是在实例里面说明下；否则真不知道。库还是不错的~~

**Comment by gouguoyin** [comment]
感谢支持，readme.md上已经进行说明了
