### ISSUE TITLE
跟GORM搭配出现报错

### ISSUE THREAD

**Issue by da4z** [golang-module/carbon#46]
```golang
package model

import (
	"github.com/golang-module/carbon"
	"gorm.io/gorm"
)

type User struct {
	ID        uint                    `gorm:"primarykey" json:"id"`
	UnionID   string                  `json:"union_id"`
	CreatedAt carbon.ToDateTimeString `json:"created_at"`
	UpdatedAt carbon.ToDateTimeString `json:"updated_at"`
	DeletedAt gorm.DeletedAt          `gorm:"index" json:"-"`
	Status    uint                    `gorm:"type:tinyint;index" json:"status"`
}

```

![捕获](https://user-images.githubusercontent.com/46473093/111327434-57c3a780-86a8-11eb-8825-4a0952ccc362.JPG)

**Comment by da4z** [comment]
看截图 ，倒数第二行数据查出来了。打印有 ，但是编码json的时候出错。看报错疑似是丢失了时区。

**Comment by gouguoyin** [comment]
你是如何给User赋值的？

**Comment by da4z** [comment]
下面赋值示例片段, 框架用的 gofiber , c.JSON框架自带  。就是json.Marshal
```golang
var user model.User
if err := db.Take(&user, 1).Error;err != nil{
    return err
}
return c.JSON(user)
```

**Comment by da4z** [comment]
看代码，用数据库拉出的时候没有赋值loc ,用一个简单例子测试了一下 。出现这个问题
https://github.com/golang-module/carbon/blob/d53cd27db8efbdb42db70e5a6132608cc73fc028/database.go#L44

![企业微信截图_20210317102314](https://user-images.githubusercontent.com/46473093/111405134-ef59e200-870a-11eb-8df7-d7dace637604.jpg)

**Comment by gouguoyin** [comment]
![image](https://user-images.githubusercontent.com/13517412/111408588-752c5c00-8710-11eb-9299-ccdc920ab39b.png)

**Comment by da4z** [comment]
请看我上面引用的代码， database 里面 Scan 可不是 catbon.Now() 带了时区的， 而是 Carbon{Time: value}
https://github.com/golang-module/carbon/blob/d53cd27db8efbdb42db70e5a6132608cc73fc028/database.go#L44

**Comment by gouguoyin** [comment]
感谢指正，Scan()应该再加上Loc
![image](https://user-images.githubusercontent.com/13517412/111410171-351aa880-8713-11eb-9dac-4b560b5efb77.png)

**Comment by da4z** [comment]
能不能发一修正版 。代码都不能愉快编写了

**Comment by gouguoyin** [comment]
马上发版

**Comment by gouguoyin** [comment]
v1.3.5已发布

**Comment by da4z** [comment]
ok, thanks

**Comment by gouguoyin** [comment]
没问题的话，麻烦给个star并关闭issus

**Comment by gouguoyin** [comment]
没问题的话，麻烦给个star并关闭issus

**Comment by da4z** [comment]
好 ，稍后我学习一下提交PR 。实现一下 sql.nulltime 接口

**Comment by gouguoyin** [comment]
v1.5.3版本已修复

**Comment by gouguoyin** [comment]
v1.5.3版本已修复
