### ISSUE TITLE
parse方法发现个bug

### ISSUE THREAD

**Issue by ayamzh** [golang-module/carbon#47]
parse方法使用的是本地时区，而没有读取carbon示例里设置的时区，carbon.sertimezone().parse("").timestamp()不正确无法根据时区变化

**Comment by gouguoyin** [comment]
timestamp()是获取时间戳的，时间戳定义为从格林威治时间1970年01月01日00时00分00秒起至现在的总秒数。地球上任何时区在任意时间点的时间戳都是相同的。但是不同时区，相同时间戳对应的当前时间不同。

**Comment by ayamzh** [comment]
举得例子可能说的不太明确
    fmt.Println(carbon.SetTimezone(carbon.LosAngeles).Parse("2020-01-01").ToTimestamp())
    fmt.Println(carbon.SetTimezone(carbon.Shanghai).Parse("2020-01-01").ToTimestamp())
期望的结果应该是上面打印的是洛杉矶1月1号对应的时间戳，下面是北京时间的1月1号对应的时间戳，实际结果2条数据一样都是取得本地时间。。。
因为底层都走的这段代码，这段代码写死了时区是local了
```
// parseByLayout 通过布局模板解析
func parseByLayout(value string, layout string) (time.Time, error) {
	loc, _ := time.LoadLocation(Local)
	tt, err := time.ParseInLocation(layout, value, loc)
	if err != nil {
		err = errors.New("the value \"" + value + "\" can't parse string as time")
	}
	return tt, err
}
```

**Comment by gouguoyin** [comment]
这里没问题，虽然parse()方法确实使用了parseBy Layout()方法，但是并没有将接收的carbon对象的Loc设置为Local。实际上，真正时区起作用的是display. go和getter. go里的方法，这些方法调用的是c. Loc

**Comment by gouguoyin** [comment]
你举的例子中，洛杉矶和北京1月1号对应的时间戳本来就是一样的，任何时区对应的时间戳都是一样的。时间戳不随时区改变而改变。

**Comment by ayamzh** [comment]
那反过来说下。。。时间戳一样，再不同时区的年月日应该一样么。？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 晚上9:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [golang-module/carbon] parse方法发现个bug (#47)




 
你举的例子中，洛杉矶和北京1月1号对应的时间戳本来就是一样的，任何时区对应的时间戳都是一样的。时间戳不随时区改变而改变。

**Comment by ayamzh** [comment]
时间戳和时区


时间戳定义为从格林威治时间1970年01月01日00时00分00秒起至现在的总秒数。

因此，严格来说，不管你处在地球上的哪个地方，任意时间点的时间戳都是相同的。这点有利于线上和客户端分布式应用统一追踪时间信息。

但是不同的时区，当前时间戳对应的当前时间是不同的。

&nbsp;
date_default_timezone_set('UTC'); var_dump(date_default_timezone_get()); //UTC var_dump(time());  //1555320581 var_dump(date('Y-m-d H:i:s')); //2019-04-15 09:29:41


&nbsp;

date_default_timezone_set('Asia/Shanghai'); var_dump(date_default_timezone_get()); //Asia/Shanghai var_dump(time());  //1555320626 var_dump(date('Y-m-d H:i:s'));  //2019-04-15 17:30:26

//两个时间戳只相差几秒，但是当前时间相差了八个小时。


&nbsp;


标签:&nbsp;php
好文要顶&nbsp;关注我&nbsp;收藏该文&nbsp;&nbsp;
web200
关注 - 0
粉丝 - 0



+加关注

1
0






»&nbsp;下一篇：&nbsp;简单理解弱类型、动态类型、解释型语言


posted @&nbsp;2019-04-15 17:32&nbsp;&nbsp;web200&nbsp; 阅读(5678)&nbsp; 评论(0)&nbsp;&nbsp;编辑&nbsp;&nbsp;收藏







---原始---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 晚上9:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [golang-module/carbon] parse方法发现个bug (#47)




 
你举的例子中，洛杉矶和北京1月1号对应的时间戳本来就是一样的，任何时区对应的时间戳都是一样的。时间戳不随时区改变而改变。

**Comment by gouguoyin** [comment]
不同时区对应的时间戳是相同的，但是同一时间戳对应不同时区的日期不同

**Comment by ayamzh** [comment]
相同日期不同时区对应的时间戳是不同的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 晚上9:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [golang-module/carbon] parse方法发现个bug (#47)




 
不同时区对应的时间戳是相同的，但是同一时间戳对应不同时区的日期不同

**Comment by ayamzh** [comment]
<?php
$dtToronto = Carbon::createFromDate(2012, 1, 1, 'America/Toronto');
$dtVancouver = Carbon::createFromDate(2012, 1, 1, 'America/Vancouver');
&nbsp;
echo $dtVancouver-&gt;diffInHours($dtToronto); // 3




手机不方便码。只能粘贴了，这是php的carbon不同时区，相同的年月日时间戳是不同的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 晚上9:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [golang-module/carbon] parse方法发现个bug (#47)




 
不同时区对应的时间戳是相同的，但是同一时间戳对应不同时区的日期不同

**Comment by open-git** [comment]
微信聊吧，gouguolei



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日(周三) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [golang-module/carbon] parse方法发现个bug (#47)




 <?php 
 $dtToronto = Carbon::createFromDate(2012, 1, 1, 'America/Toronto'); 
 $dtVancouver = Carbon::createFromDate(2012, 1, 1, 'America/Vancouver'); 
 &amp;nbsp; 
 echo $dtVancouver-&amp;gt;diffInHours($dtToronto); // 3 
 
 
 
 
 手机不方便码。只能粘贴了，这是php的carbon不同时区，相同的年月日时间戳是不同的 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年3月17日(周三) 晚上9:17 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [golang-module/carbon] parse方法发现个bug (#47) 
 
 
 
 
   
 不同时区对应的时间戳是相同的，但是同一时间戳对应不同时区的日期不同

**Comment by gouguoyin** [comment]
已修复
