### ISSUE TITLE
parse的bug

### ISSUE THREAD

**Issue by ayamzh** [golang-module/carbon#48]
parse方法使用的是本地时区，而没有读取carbon示例里设置的时区，carbon.sertimezone().parse("")  得到的不是指定时区的对象，而是local时区的。。。。

**Comment by ayamzh** [comment]
parse 底层时区用的loc, _ := time.LoadLocation(Local) 。 应该读取carbon.loc才能支持时区变化。

**Comment by gouguoyin** [comment]
已修复
