### ISSUE TITLE
carbon.Parse("2020-08-05 13:14:15").DiffForHumans(carbon.Now())测试返回空白

### ISSUE THREAD

**Issue by hansonwong** [golang-module/carbon#52]
carbon.Parse("2020-08-05 13:14:15").DiffForHumans(carbon.Now())测试返回空白

**Comment by gouguoyin** [comment]
![image](https://user-images.githubusercontent.com/13517412/112713579-d9210280-8f10-11eb-9ebb-64caa6a41c1e.png)

**Comment by hansonwong** [comment]
测试可以了，谢谢

**Comment by hansonwong** [comment]
carbon项目有lang,  能改进直接读取吗

**Comment by gouguoyin** [comment]
> 测试可以了，谢谢

可以的话麻烦给个star

**Comment by hansonwong** [comment]
已start, 支持，好用的

**Comment by gouguoyin** [comment]
> carbon项目有lang, 能改进直接读取吗

有规划用go1.16的go:embed指令将lang翻译资源内嵌进去

**Comment by hansonwong** [comment]
![image](https://user-images.githubusercontent.com/11640723/112713870-5a2cc980-8f12-11eb-9858-ba4be6c16c12.png)
之前写了这个，还是你这个好用的

**Comment by hansonwong** [comment]
> > carbon项目有lang, 能改进直接读取吗
> 
> 有规划用go1.16的go:embed指令将lang翻译资源内嵌进去

牛逼！我是菜鸟

**Comment by hansonwong** [comment]
![image](https://user-images.githubusercontent.com/11640723/112714328-d32d2080-8f14-11eb-9832-66338e5b7ad7.png)
 短短几包就能解决问题
![image](https://user-images.githubusercontent.com/11640723/112714338-e5a75a00-8f14-11eb-83fd-0b3b2a7005be.png)

**Comment by gouguoyin** [comment]
推荐对Parse（）方法进行错误判断，因为传入的时间字符串不一定合法。另外

DiffForHumans方法不传参默认就是和当前时间对比，所以没必要再传carbon. Now


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月27日(周六) 下午3:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [golang-module/carbon] carbon.Parse("2020-08-05 13:14:15").DiffForHumans(carbon.Now())测试返回空白 (#52)




 

 短短几包就能解决问题

**Comment by gouguoyin** [comment]
建议写法
c：= carbon. SetLocale（zh-CN）. Parse（t）
if c. Error ！= nil ｛
    //错误处理
｝
return c. DiffForHumans（）

**Comment by gouguoyin** [comment]
如何不想把lang目录复制到当前项目目录下，可以这样写

> lang := NewLanguage()
resources := map[string]string {
        "year":"%d 年",
	"month":"%d 个月",
	"week":"%d 周",
	"day":"%d 天",
	"hour":"%d 小时",
	"minute":"%d 分钟",
	"second":"%d 秒",
	"now": "刚刚",
	"ago":"%s前",
	"from_now":"%s后",
	"before":"%s前",
	"after":"%s后"
}
lang.SetResources(resources)
carbon.Now().SetLanguage(lang).DiffForHumans()

**Comment by gouguoyin** [comment]
> ![image](https://user-images.githubusercontent.com/11640723/112714328-d32d2080-8f14-11eb-9832-66338e5b7ad7.png)
> 短短几包就能解决问题
> ![image](https://user-images.githubusercontent.com/11640723/112714338-e5a75a00-8f14-11eb-83fd-0b3b2a7005be.png)

建议写法

> c := carbon.SetLocale("zh-CN").Parse(t)
if c. Error ！= nil ｛
    //错误处理
｝
return c. DiffForHumans()

**Comment by hansonwong** [comment]
已改进，多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "golang-module/carbon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月27日(星期六) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [golang-module/carbon] carbon.Parse("2020-08-05 13:14:15").DiffForHumans(carbon.Now())测试返回空白 (#52)





  

 短短几包就能解决问题
 
  
建议写法
  
c := carbon.SetLocale("zh-CN").Parse(t)
 if c. Error ！= nil ｛
 //错误处理
 ｝
 return c. DiffForHumans()

**Comment by gouguoyin** [comment]
Since version 1.5.0, it is no longer necessary to copy the lang directory to the project directory
