### ISSUE TITLE
carbon.Carbon, 调用IsZero panic

### ISSUE THREAD

**Issue by WilliamYang1992** [golang-module/carbon#53]
![image](https://user-images.githubusercontent.com/19986480/113650502-e2556080-96c2-11eb-8922-7fed9f0fdb3f.png)

我要判断时间是否为 零值，但是默认的 Location 为 nil，导致 panic 了，望修复，谢谢！

**Comment by gouguoyin** [comment]
能把业务代码贴下么

**Comment by WilliamYang1992** [comment]
你好，我写了简例
![image](https://user-images.githubusercontent.com/19986480/113652581-9dcbc400-96c6-11eb-9b29-7987a1376572.png)

**Comment by gouguoyin** [comment]
你本地先改成试下

> func (c Carbon) IsZero() bool {
	return c.Time.IsZero()
}

**Comment by gouguoyin** [comment]
你先本地试下，还有没有其他问题，没问题我晚会发个小版本

**Comment by WilliamYang1992** [comment]
我就是这样改的，没问题

**Comment by gouguoyin** [comment]
你先if ！parameter.Data.Time.IsZero（）这样判断，下个版本会修复这个bug，昨天刚发版，今天再发版太频繁了。

**Comment by gouguoyin** [comment]
感谢你的使用和指正，如果发现有其他bug或者有新的功能需求，欢迎指出。

**Comment by WilliamYang1992** [comment]
好的，谢谢

**Comment by gouguoyin** [comment]
v1.3.7版本已修复

**Comment by gouguoyin** [comment]
没问题麻烦给个star

**Comment by WilliamYang1992** [comment]
我早就给了star 啊，😄



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gouguoyin ***@***.***&gt;
发送时间: 2021年4月10日 15:44
收件人: golang-module/carbon ***@***.***&gt;
抄送: William Yang ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[golang-module/carbon] carbon.Carbon, 调用IsZero panic (#53)





 
没问题麻烦给个star

**Comment by gouguoyin** [comment]
好的，感谢支持
