### ISSUE TITLE
format 如何设置时间长度？

### ISSUE THREAD

**Issue by hjzCy** [golang-module/carbon#57]
```go
toady := carbon.Now()
f := toady.Format("U.u")   // => 1618396403.312
```

假如想让 **毫秒长度** 保留到6位该如何写？

**Comment by gouguoyin** [comment]
你是要获取毫秒级时间戳还是当前的毫秒？

**Comment by hjzCy** [comment]
> 你是要获取毫秒级时间戳还是当前的毫秒？

我想获得浮点型的时间戳，单位是秒，但是要可以选择保留尾数毫秒的长度。

**Comment by gouguoyin** [comment]
用strconv.FormatFloat保留小数点位数

**Comment by gouguoyin** [comment]
用strconv.FormatFloat保留小数点位数

**Comment by gouguoyin** [comment]
用strconv.FormatFloat保留小数点位数

**Comment by gouguoyin** [comment]
用strconv.FormatFloat保留小数点位数

**Comment by gouguoyin** [comment]
用strconv.FormatFloat保留小数点位数

**Comment by hjzCy** [comment]
@gouguoyin 然后这里最多只显示到3位，我需要的保留尾数的超过了3位。例如 1618396403.3122254 这样更精确的尾数。

**Comment by gouguoyin** [comment]
你说的是微妙吧，毫秒是3位数，微妙是6位数

> 1秒=1000毫秒(ms), 1毫秒=1／1000秒(s)；
> 1秒=1000000 微秒(μs), 1微秒=1／1000000秒(s)；
> 1秒=1000000000 纳秒(ns),1纳秒=1／1000000000秒(s)；
> 1秒=1000000000000皮秒 1皮秒==1/1000000000000秒。
