### ISSUE TITLE
how to parse time string with a timezone and output with another timezone

### ISSUE THREAD

**Issue by mailbaoer** [golang-module/carbon#60]
I want to parse a time string with timezone `Asia/Shanghai` and output with timezone utc how can I do this correctly?

**Comment by moulo1982** [comment]
t := carbon.SetTimezone(carbon.UTC).Now()
fmt.Printf("%s\n", t.ToDateTimeString())
fmt.Printf("%s\n", t.SetTimezone(carbon.LosAngeles).ToDateTimeString())
fmt.Printf("%s\n", t.SetTimezone(carbon.Shanghai).ToDateTimeString())


2021-05-31 13:22:57
2021-05-31 06:22:57
2021-05-31 21:22:57

**Comment by mailbaoer** [comment]
👍 thank you very much!

**Comment by gouguoyin** [comment]
v1.3.8版本已新增ToXXXStriingWithTimezone()方法，如
`carbon.Parse("2020-08-05 13:14:15").ToDateTimeStringWithTimezone(carbon.LosAngeles) // 2020-08-04 22:14:15`

**Comment by mailbaoer** [comment]
when I want to save time without timezone to database, but when client send time string with their local timezone , I found another problem with code below:
```go
a := carbon.SetTimezone(carbon.Shanghai).Parse("2021-07-01 10:00:05") 
fmt.Println(a.SetTimezone(carbon.UTC).Time)
fmt.Println(a.SetTimezone(carbon.UTC).ToDateTimeString())
```
the output:
```
2021-07-01 12:00:05 +0800 CST
2021-07-01 04:00:05
```
my system timezone is `Asia/Shanghai`

**Comment by mailbaoer** [comment]
sloved, just use `fmt.Println(a.SetTimezone(carbon.UTC).Carbon2Time())`

**Comment by gouguoyin** [comment]
> sloved, just use `fmt.Println(a.SetTimezone(carbon.UTC).Carbon2Time())`
You can use it like this：
`carbon.SetTimezone(carbon.Shanghai).Parse("2021-07-01 10:00:05") .ToDateTimeStringWithTimezone(carbon.UTC))`

**Comment by mailbaoer** [comment]
Thank you! But I want a time.Time format to save in my postgresql database, not a time string ,so can't use `ToDateTimeStringWithTimezone` method
