### ISSUE TITLE
中文环境下,如何将周日作为一周的开始,周六作为一周的结束

### ISSUE THREAD

**Issue by ehomecd** [golang-module/carbon#62]
中文环境下,
StartOfMonth()
EndOfWeek()
这两个方法,如何将周日作为一周的开始,周六作为一周的结束

**Comment by gouguoyin** [comment]
v1.3.9版本已支持
// 本周开始时间
carbon.Parse("2020-08-05 13:14:15").StartOfWeek(time.Sunday).ToDateTimeString() // 2020-08-02 00:00:00
carbon.Parse("2020-08-05 13:14:15").StartOfWeek(time.Monday).ToDateTimeString() // 2020-08-03 00:00:00
// 本周结束时间
carbon.Parse("2020-08-05 13:14:15").EndOfWeek(time.Sunday).ToDateTimeString() // 2020-08-08 23:59:59
carbon.Parse("2020-08-05 13:14:15").EndOfWeek(time.Monday).ToDateTimeString() // 2020-08-09 23:59:59
