### ISSUE TITLE
希望添加 UnmarshalJSON

### ISSUE THREAD

**Issue by kuang1055wei** [golang-module/carbon#63]

**Comment by gouguoyin** [comment]
使用场景描述下

**Comment by kuang1055wei** [comment]
结构体定义ToDateTimeString，转换成json，没问题，因为实现MarshalJSON。
json转换为结构体，没有实现UnmarshalJSON，无法直接转换为ToDateTimeString

**Comment by gouguoyin** [comment]
json转结构体时，需要先定义结构体，定义结构体时字段类型不就定义了么？

**Comment by kuang1055wei** [comment]
已经定义了。现在 解决方案如下。
`type DateTime struct {
	carbon.Carbon
}

func (c DateTime) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf(`"%s"`, c.ToDateTimeString())), nil
}

func (t *DateTime) UnmarshalJSON(b []byte) error {
	*t = DateTime{carbon.Parse(strings.ReplaceAll(string(b), "\"", ""))}
	return nil
}
`

**Comment by gouguoyin** [comment]
> 已经定义了。现在 解决方案如下。
> `type DateTime struct {
> carbon.Carbon
> }
> 
> func (c DateTime) MarshalJSON() ([]byte, error) {
> return []byte(fmt.Sprintf(`"%s"`, c.ToDateTimeString())), nil
> }
> 
> func (t *DateTime) UnmarshalJSON(b []byte) error {
> *t = DateTime{carbon.Parse(strings.ReplaceAll(string(b), """, ""))}
> return nil
> }
> `

接收json解析后的结构体是如何定义的？

**Comment by gouguoyin** [comment]
v1.4.3版本已支持

**Comment by kuang1055wei** [comment]
nice
