### ISSUE TITLE
carbon format 错误

### ISSUE THREAD

**Issue by waising** [golang-module/carbon#65]
ts := carbon.Time2Carbon(time.Now())
tStr := ts.Format("2006-01-02 15:04:05")
fmt.Println(tStr)

tStr输出不是当前时间  而是 2006-01-02 15:04:05

**Comment by gouguoyin** [comment]
仔细看说明文档，Format()不是这样用的,你如果是想输出标准时间格式，使用ts.Format("Y-m-d H:i:s")或ts. ToDateTimeString()
