### ISSUE TITLE
似乎不支持 [swaggo/swag](https://github.com/swaggo/swag) 生成文档

### ISSUE THREAD

**Issue by shuqingzai** [golang-module/carbon#66]
无法解析结构体属性中的 error，导致无法生成swagger文档，是否可以兼容？
![image](https://user-images.githubusercontent.com/44406033/124430817-39420300-dda2-11eb-86ca-8880404e91ce.png)
![image](https://user-images.githubusercontent.com/44406033/124430839-3f37e400-dda2-11eb-91e8-e494f9f671fa.png)
![image](https://user-images.githubusercontent.com/44406033/124430874-48c14c00-dda2-11eb-8a10-14cc8577947a.png)
![image](https://user-images.githubusercontent.com/44406033/124430931-5b3b8580-dda2-11eb-8ea5-0990a06a557a.png)

**Comment by gouguoyin** [comment]
有详细的报错堆栈么？

**Comment by shuqingzai** [comment]
应该是swaggo不支持解析 error类型

**Comment by gouguoyin** [comment]
> 应该是swaggo不支持解析 error类型

那是不是应该给swaggo提个issue兼容下error类型？
