### ISSUE TITLE
Very good package. Time zone seems incomplete

### ISSUE THREAD

**Issue by jinsuojinsuo** [golang-module/carbon#67]
Very good package. Time zone seems incomplete

**Comment by gouguoyin** [comment]
carbon只定义了常见的时区常量，未被定义的时区，可以用原始字符串即可，所有支持的时区可以将$GOROOT/lib/time/zoneinfo.zip解压查看

> carbon.SetTimezone("Libya") or carbon.SetTimezone("Asia/Saigon")
