### ISSUE TITLE
google.protobuf.Timestamp和gorm，time.Time之间的转换有吗？

### ISSUE THREAD

**Issue by yueqianlong** [golang-module/carbon#68]
proto文件里的google.protobuf.Timestamp和gorm，time.Time之间的转换有吗？

**Comment by gouguoyin** [comment]
没有

**Comment by gouguoyin** [comment]
你想要这三者如何转换？

**Comment by yueqianlong** [comment]
比如，
proto文件里的定义的一个时间字段google.protobuf.Timestamp  registerDate ，
对应go定义的结构体里的一个字段RegisterDate  time.Time  `gorm:"column:register_date;"`
也对应数据库(mysql)里的一个字段register_date  datetime，
这三者时间转换问题

**Comment by yueqianlong** [comment]
比如，
proto文件里的定义的一个时间字段google.protobuf.Timestamp  registerDate ，
对应go定义的结构体里的一个字段RegisterDate  time.Time  `gorm:"column:register_date;"`
也对应数据库(mysql)里的一个字段register_date  datetime，
这三者时间转换问题

**Comment by gouguoyin** [comment]
After careful consideration, this function will not be added.
