### ISSUE TITLE
carbon根据指定格式输出时间字符串有问题

### ISSUE THREAD

**Issue by YuXiaoCoder** [golang-module/carbon#73]
carbon version: 1.3.9 or 1.4.2

dataTime := carbon.Now().ToFormatString("Mon, 02 Jan 2006 15:04:05 GMT")
fmt.Println(dataTime)
output: Julo7, 02 Jpm7 2006 15:04:05 17JulCST

dataTime = time.Now().Format("Mon, 02 Jan 2006 15:04:05 GMT")
fmt.Println(dataTime)
output: Thu, 22 Jul 2021 17:45:54 GMT

**Comment by gouguoyin** [comment]
ToFormatString()方法用错了，该方法支持的格式是Y-m-d H:i:s这样的字符，所有支持的字符请查看[格式化符号表](https://github.com/golang-module/carbon#%E6%A0%BC%E5%BC%8F%E5%8C%96%E7%AC%A6%E5%8F%B7%E8%A1%A8 "格式化符号表")
"Mon, 02 Jan 2006 15:04:05 GMT"明显是一个RFC7231格式，可以用carbon.Now().ToRfc7231String()

**Comment by gouguoyin** [comment]
v1.4.4版本中还可以使用carbon.Now().Layout("Mon, 02 Jan 2006 15:04:05 GMT")
