### ISSUE TITLE
carbon.Now().ToMonthString() is null

### ISSUE THREAD

**Issue by arden** [golang-module/carbon#82]
println(carbon.Now().ToMonthString())
println(carbon.Now().ToWeekString())

这两个方法打印出来都是空的。

**Comment by gouguoyin** [comment]
Please refer to issue #52

**Comment by gouguoyin** [comment]
Since version 1.5.0, it is no longer necessary to copy the lang directory to the project directory

**Comment by liaohongxing** [comment]
thx
