### ISSUE TITLE
紧急问题, 升级V1.5.0之后, ToDateTimeString 出错

### ISSUE THREAD

**Issue by liaohongxing** [golang-module/carbon#86]
把 carbon.ToDateTimeString 用作时间字段,全站全崩

```go
type Class struct {
	ID          int                         `gorm:"primarykey" json:"id" form:"id"`
	Name        string                      `gorm:"size:80" json:"name" form:"name"`
	CreatedAt   carbon.ToDateTimeString     `json:"created_at" form:"created_at"`
	UpdatedAt   carbon.ToDateTimeString     `json:"updated_at" form:"updated_at"`
	Status      int8                        `gorm:"index" json:"status" form:"status"`
}
```

v1.5.0 直接报错。之前的版本没有问题，报错信息:

`time: missing Location in call to Time.In`

疑似跟最近一次更新有关:

https://github.com/golang-module/carbon/commit/63ac859a46297ef7bdc0427f72332865b7ef466e#diff-3a959176e85691e2f895b56153bc13c863f1e95acc0476a53affd12ad7fb1be7

**Comment by liaohongxing** [comment]
似乎 Scan 的时候 c.loc 是空的

**Comment by gouguoyin** [comment]
This problem does exist, version 1.5.1 will be released today and this bug will be fixed together.

**Comment by gouguoyin** [comment]
V1.5.1 has been released, please upgrade and try again

**Comment by gouguoyin** [comment]
Have you solved it?
