### ISSUE TITLE
might like this video about time keeping

### ISSUE THREAD

**Issue by gedw99** [golang-module/carbon#88]
part 1: https://www.youtube.com/watch?v=6pJlQLSKjbc&t=0s

part 2: https://www.youtube.com/watch?v=Gr7sZ4MPMu8

**Comment by gouguoyin** [comment]
what？

**Comment by gedw99** [comment]
It’s about hardware that is now open source to keep nanosecond precise time on your servers.

figured it’s sort of interesting to you.

min distributed systems we as developers have to design for in order transactions and having time being precise in our servers gives those guarantees.

so this is not an issue about your code :)
