### ISSUE TITLE
关于today , yesterday的疑问

### ISSUE THREAD

**Issue by ysxpark** [golang-module/carbon#98]
php版本的today和yesterday返回的是今天开始时间和昨天开始时间,
此库的yesterday返回的是昨天此刻,是不是不太好,
用此库就是为了解决比较难用标准库的获取的时间
昨天此刻完全可以用carbon.Now().SubDay()来实现
但是获取今天开始时间或者昨天开始时间怎么获取?

**Comment by gouguoyin** [comment]
```
carbon.Now(). StartOfDay() 
carbon. Yesterday(). EndOfDay()
```

**Comment by ysxpark** [comment]
感谢
