### ISSUE TITLE
支持一下阴历转阳历呗

### ISSUE THREAD

**Issue by jan-bar** [golang-module/carbon#99]
## Feature Request
您的代码貌似只实现了阳历转阴历，这个库实现了阴历转阳历：[solarlunar](https://github.com/nosixtools/solarlunar)

有计算阴历的下一年的需求。最好有个传入阴历年月日，得到对象，计算下一年当前阴历的对象额。

**Comment by jan-bar** [comment]
对了，还有`干支年`，`干支月`，`干支日`，这类阴历的属性。虽然我没用上，但也是阴历的一个属性额。

**Comment by gouguoyin** [comment]
后期版本会逐步添加

**Comment by jan-bar** [comment]
> 后期版本会逐步添加

等不及了，我爬取百度万年历数据，存入数据库。直接查表弄好了。。。反正都活都搞定就好。。。
<https://github.com/jan-bar/interesting/tree/master/perpetual_calendar>
